{ pkgs, lib, ... }:

let
  # Build the Rust backend
  backend = pkgs.rustPlatform.buildRustPackage {
    pname = "amirsalarsafaeicom-backend";
    version = "0.1.0";
    
    src = lib.cleanSourceWith {
      src = ./..;
      filter = path: type:
        let
          baseName = baseNameOf path;
          relPath = lib.removePrefix (toString ./.. + "/") path;
        in
          # Include backend source
          (lib.hasPrefix "backend" relPath) ||
          # Include autogenerated rust code
          (lib.hasPrefix "autogenerated/rust" relPath) ||
          # Include proto files for build
          (lib.hasPrefix "proto" relPath) ||
          # Include root Cargo workspace files
          relPath == "Cargo.toml" ||
          relPath == "Cargo.lock" ||
          # Allow traversing into autogenerated directory
          relPath == "autogenerated";
    };

    cargoLock = {
      lockFile = ../Cargo.lock;
    };

    buildAndTestSubdir = "backend";

    nativeBuildInputs = with pkgs; [
      pkg-config
      protobuf
    ];

    buildInputs = with pkgs; [
      openssl
      postgresql
    ];

    PROTOC = "${pkgs.protobuf}/bin/protoc";
    OPENSSL_NO_VENDOR = "1";
    
    # Skip tests during build
    doCheck = false;
  };

in {
  package = backend;

  # Container image for the backend
  image = pkgs.dockerTools.buildLayeredImage {
    name = "amirsalarsafaeicom-backend";
    tag = "latest";

    contents = with pkgs; [
      backend
      cacert
      tzdata
    ];

    config = {
      Entrypoint = [ "${backend}/bin/amirsalarsafaeicom-backend" ];
      Cmd = [ "--config-path" "/config/config.toml" "--spotify-cred-path" "/config/spotify.toml" ];
      ExposedPorts = {
        "8000/tcp" = {};
        "3001/tcp" = {};
      };
      Env = [
        "SSL_CERT_FILE=${pkgs.cacert}/etc/ssl/certs/ca-bundle.crt"
        "RUST_LOG=info"
      ];
      WorkingDir = "/app";
      Volumes = {
        "/app/uploads" = {};
        "/config" = {};
      };
    };

    extraCommands = ''
      mkdir -p app/uploads
      mkdir -p config
    '';
  };
}
