{
  pkgs,
  lib,
  src,
  ...
}:

let
  backend = pkgs.rustPlatform.buildRustPackage {
    pname = "amirsalarsafaeicom-backend";
    version = "0.1.0";

    src = lib.cleanSourceWith {
      inherit src;
      filter =
        path: type:
        let
          baseName = baseNameOf path;
          relPath = lib.removePrefix (toString src + "/") path;
        in
        (lib.hasPrefix "backend" relPath)
        || (lib.hasPrefix "autogenerated/rust" relPath)
        || (lib.hasPrefix "proto" relPath)
        || relPath == "Cargo.toml"
        || relPath == "Cargo.lock"
        || relPath == "autogenerated";
    };

    cargoLock = {
      lockFile = "${src}/Cargo.lock";
    };

    buildAndTestSubdir = "backend";

    nativeBuildInputs = with pkgs; [
      pkg-config
      protobuf
    ];

    buildInputs = with pkgs; [
      openssl
      postgresql
    ];

    PROTOC = "${pkgs.protobuf}/bin/protoc";
    OPENSSL_NO_VENDOR = "1";

    doCheck = false;
  };

in
{
  package = backend;

  image = pkgs.dockerTools.buildLayeredImage {
    name = "amirsalarsafaeicom-backend";
    tag = "latest";

    contents = with pkgs; [
      backend
      cacert
      tzdata
    ];

    config = {
      Entrypoint = [ "${backend}/bin/amirsalarsafaeicom-backend" ];
      Cmd = [
        "--config-path"
        "/config/config.toml"
        "--spotify-cred-path"
        "/config/spotify.toml"
      ];
      ExposedPorts = {
        "8000/tcp" = { };
        "3001/tcp" = { };
      };
      Env = [
        "SSL_CERT_FILE=${pkgs.cacert}/etc/ssl/certs/ca-bundle.crt"
        "RUST_LOG=info"
      ];
      WorkingDir = "/app";
      Volumes = {
        "/app/uploads" = { };
        "/config" = { };
      };
    };

    extraCommands = ''
      mkdir -p app/uploads
      mkdir -p config
    '';
  };
}
