{ pkgs, lib, src, ... }:

let
  nodejs = pkgs.nodejs_20;

  frontendSrc = lib.cleanSourceWith {
    inherit src;
    filter = path: type:
      let
        baseName = baseNameOf path;
        relPath = lib.removePrefix (toString src + "/") path;
      in
        (lib.hasPrefix "frontend" relPath) ||
        (lib.hasPrefix "autogenerated/ts" relPath) ||
        relPath == "autogenerated" ||
        relPath == "autogenerated/package.json" ||
        relPath == "autogenerated/yarn.lock";
  };

  frontend = pkgs.mkYarnPackage {
    pname = "amirsalarsafaei-frontend";
    version = "0.1.0";

    src = "${frontendSrc}/frontend";

    packageJSON = "${src}/frontend/package.json";
    yarnLock = "${src}/frontend/yarn.lock";

    nativeBuildInputs = with pkgs; [
      pkg-config
      python3
    ];

    buildInputs = with pkgs; [
      vips
      libiconv
    ] ++ lib.optionals pkgs.stdenv.isDarwin [
      pkgs.darwin.apple_sdk.frameworks.CoreServices
    ];

    preBuild = ''
      # Copy autogenerated files to the expected location relative to frontend
      mkdir -p deps/@amirsalarsafaei/frontend/../autogenerated
      cp -r ${frontendSrc}/autogenerated/ts deps/@amirsalarsafaei/autogenerated/ || true
      
      # Also copy to parent for the relative path resolution
      mkdir -p deps/autogenerated
      cp -r ${frontendSrc}/autogenerated/ts deps/autogenerated/ || true
    '';

    buildPhase = ''
      runHook preBuild

      export HOME=$TMPDIR
      cd deps/@amirsalarsafaei/frontend

      # Ensure autogenerated is accessible via the path alias
      mkdir -p ../autogenerated
      cp -r ${frontendSrc}/autogenerated/ts ../autogenerated/ || true

      yarn build

      runHook postBuild
    '';

    installPhase = ''
      runHook preInstall

      mkdir -p $out

      if [ -d ".next/standalone" ]; then
        cp -r .next/standalone/* $out/

        mkdir -p $out/.next/static
        cp -r .next/static/* $out/.next/static/

        if [ -d "public" ]; then
          cp -r public $out/
        fi
      else
        cp -r .next $out/
        cp -r node_modules $out/ || true
        cp package.json $out/
        if [ -d "public" ]; then
          cp -r public $out/
        fi
      fi

      runHook postInstall
    '';

    distPhase = "true";
    dontFixup = true;
  };

in
{
  package = frontend;

  image = pkgs.dockerTools.buildLayeredImage {
    name = "amirsalarsafaeicom-frontend";
    tag = "latest";

    contents = with pkgs; [
      frontend
      nodejs
      cacert
      tzdata
      bash
      coreutils
    ];

    config = {
      Entrypoint = [ "${nodejs}/bin/node" ];
      Cmd = [ "/app/server.js" ];
      ExposedPorts = {
        "3000/tcp" = { };
      };
      Env = [
        "NODE_ENV=production"
        "PORT=3000"
        "HOSTNAME=0.0.0.0"
        "SSL_CERT_FILE=${pkgs.cacert}/etc/ssl/certs/ca-bundle.crt"
      ];
      WorkingDir = "/app";
    };

    extraCommands = ''
      mkdir -p app
      cp -r ${frontend}/* app/ || true
      cp -r ${frontend}/.next app/.next || true
    '';
  };
}
