{ pkgs, lib, ... }:

let
  nodejs = pkgs.nodejs_20;
  
  # Frontend source
  frontendSrc = lib.cleanSourceWith {
    src = ./..;
    filter = path: type:
      let
        baseName = baseNameOf path;
        relPath = lib.removePrefix (toString ./.. + "/") path;
      in
        # Include frontend source
        (lib.hasPrefix "frontend" relPath) ||
        # Include autogenerated ts code
        (lib.hasPrefix "autogenerated/ts" relPath) ||
        (lib.hasPrefix "autogenerated/package.json" relPath) ||
        (lib.hasPrefix "autogenerated/yarn.lock" relPath);
  };

  # Use mkYarnPackage for proper offline yarn builds
  frontend = pkgs.mkYarnPackage {
    pname = "amirsalarsafaeicom-frontend";
    version = "0.1.0";
    
    src = "${frontendSrc}/frontend";

    packageJSON = ../frontend/package.json;
    yarnLock = ../frontend/yarn.lock;

    nativeBuildInputs = with pkgs; [
      pkg-config
      python3
    ];

    buildInputs = with pkgs; [
      vips
      libiconv
    ] ++ lib.optionals stdenv.isDarwin [
      darwin.apple_sdk.frameworks.CoreServices
    ];

    buildPhase = ''
      runHook preBuild
      
      export HOME=$TMPDIR
      cd deps/@amirsalarsafaei/frontend
      
      # Build Next.js
      yarn build
      
      runHook postBuild
    '';

    installPhase = ''
      runHook preInstall
      
      mkdir -p $out
      
      # Copy standalone build
      if [ -d ".next/standalone" ]; then
        cp -r .next/standalone/* $out/
        
        # Copy static assets
        mkdir -p $out/.next/static
        cp -r .next/static/* $out/.next/static/
        
        # Copy public assets
        if [ -d "public" ]; then
          cp -r public $out/
        fi
      else
        # Fallback: copy required files
        cp -r .next $out/
        cp -r node_modules $out/ || true
        cp package.json $out/
        if [ -d "public" ]; then
          cp -r public $out/
        fi
      fi
      
      runHook postInstall
    '';

    distPhase = "true";
    dontFixup = true;
  };

in {
  package = frontend;

  # Container image for the frontend
  image = pkgs.dockerTools.buildLayeredImage {
    name = "amirsalarsafaeicom-frontend";
    tag = "latest";

    contents = with pkgs; [
      frontend
      nodejs
      cacert
      tzdata
      bash
      coreutils
    ];

    config = {
      Entrypoint = [ "${nodejs}/bin/node" ];
      Cmd = [ "/app/server.js" ];
      ExposedPorts = {
        "3000/tcp" = {};
      };
      Env = [
        "NODE_ENV=production"
        "PORT=3000"
        "HOSTNAME=0.0.0.0"
        "SSL_CERT_FILE=${pkgs.cacert}/etc/ssl/certs/ca-bundle.crt"
      ];
      WorkingDir = "/app";
    };

    extraCommands = ''
      mkdir -p app
      cp -r ${frontend}/* app/ || true
      cp -r ${frontend}/.next app/.next || true
    '';
  };
}
