{
  projectRootFile = "flake.nix";

  programs = {
    nixfmt.enable = true;
    rustfmt.enable = true;
    prettier.enable = true;
  };

  settings.formatter = {
    prettier = {
      includes = [
        "*.json"
        "*.md"
        "*.yaml"
        "*.yml"
        "frontend/**/*.ts"
        "frontend/**/*.tsx"
        "frontend/**/*.js"
        "frontend/**/*.jsx"
      ];
      excludes = [
        "node_modules/**"
        "**/.next/**"
        "autogenerated/**"
        "frontend/yarn.lock"
        "autogenerated/yarn.lock"
      ];
    };
  };
}
