# amirsalarsafaei.com — task runner. Run `just` to list recipes.

# NixOS has no FHS /bin/bash; resolve bash from PATH via env.
set shell := ["/usr/bin/env", "bash", "-cu"]

_default:
    @just --list --unsorted

# ─── Protobuf ───────────────────────────────────────────────────────────────

# Regenerate gRPC code (TS + Rust + Go) from proto/
buf-generate: clean
    @mkdir -p autogenerated/ts autogenerated/rust/src autogenerated/go
    buf generate
    cd autogenerated/go && go mod tidy

# Lint .proto files
buf-lint:
    buf lint

# Check for breaking proto changes vs main
buf-breaking:
    buf breaking --against '.git#branch=main'

# Remove generated proto code
clean:
    rm -rf autogenerated/ts autogenerated/rust

# ─── Build / dev ────────────────────────────────────────────────────────────

# Build backend + frontend + tuissh server locally
build:
    cargo build --workspace
    cd frontend && yarn build
    cd tuissh && go build ./...

# Run backend locally (cargo run)
backend:
    cd backend && cargo run

# Run frontend dev server (yarn dev)
frontend:
    cd frontend && yarn dev

# Run the tuissh server locally (connect: ssh -p 23234 localhost). Set GRPC_ADDR
# to point at a running backend (default localhost:8000).
tuissh:
    cd tuissh && go run .

# Run all tests
test:
    cargo test --workspace -- --show-output
    cd tuissh && go test ./...

# Run clippy + next lint + go vet
lint:
    cargo clippy --workspace -- -D warnings
    cd frontend && yarn lint
    cd tuissh && go vet ./...

# Format the whole tree (treefmt)
format:
    treefmt

# ─── Nix ────────────────────────────────────────────────────────────────────

# Recompute the yarn offline cache + Go vendor hashes (no full build) and write
# them into nix/packages/. Run after changing frontend/yarn.lock or tuissh/go.{mod,sum}.
update-nix-hashes:
    ./nix/update-hashes.sh

# ─── Database ───────────────────────────────────────────────────────────────

# Apply sqlx migrations to $DATABASE_URL
db-migrate:
    cd backend && sqlx migrate run

# Refresh .sqlx offline query cache
db-prepare:
    cargo sqlx prepare --workspace

# ─── Docker ─────────────────────────────────────────────────────────────────

# Build backend + frontend images
docker-build:
    docker compose build

# Start all services (postgres, backend, frontend)
up:
    docker compose up -d

# Stop and remove containers
down:
    docker compose down

# Tail logs from all services
logs:
    docker compose logs -f

# Dev stack fully in Docker (use this, NOT `docker compose --profile dev up`)
dev:
    docker compose --profile dev up -d postgres backend frontend-dev

# Backend only in Docker (postgres + migrate + backend)
backends:
    docker compose up -d backend

# Backends in Docker + frontend on the host with hot reload (the usual setup)
dev-local: backends
    cd frontend && yarn install && yarn dev

# ─── Deploy ─────────────────────────────────────────────────────────────────

# Build images locally and push to remote host via SSH
deploy-docker: docker-build
    docker save amirsalarsafaeicom-backend:local amirsalarsafaeicom-frontend:local amirsalarsafaeicom-tuissh:local \
        | gzip \
        | ssh finRoot "gunzip | docker load"

# Sync source tree to VPS for in-place builds
deploy-rsync:
    rsync -avzP \
        --exclude='.git/' --exclude='.direnv/' --exclude='.devbox/' \
        --exclude='frontend/node_modules' --exclude='frontend/.next' \
        --exclude='backend/target' --exclude='target/' \
        --exclude='node_modules/' --exclude='backend/uploads' \
        . finRoot:/root/amirsalarsafaei.com/
