# amirsalarsafaei.com — task runner. Run `just` to list recipes.

set shell := ["bash", "-cu"]

_default:
    @just --list --unsorted

# ─── Protobuf ───────────────────────────────────────────────────────────────

# Regenerate gRPC code (TS + Rust) from proto/
buf-generate: clean
    @mkdir -p autogenerated/ts autogenerated/rust/src
    buf generate

# Lint .proto files
buf-lint:
    buf lint

# Check for breaking proto changes vs main
buf-breaking:
    buf breaking --against '.git#branch=main'

# Remove generated proto code
clean:
    rm -rf autogenerated/ts autogenerated/rust

# ─── Build / dev ────────────────────────────────────────────────────────────

# Build backend + frontend locally
build:
    cargo build --workspace
    cd frontend && yarn build

# Run backend locally (cargo run)
backend:
    cd backend && cargo run

# Run frontend dev server (yarn dev)
frontend:
    cd frontend && yarn dev

# Run all tests
test:
    cargo test --workspace -- --show-output

# Run clippy + next lint
lint:
    cargo clippy --workspace -- -D warnings
    cd frontend && yarn lint

# Format the whole tree (treefmt)
format:
    treefmt

# ─── Database ───────────────────────────────────────────────────────────────

# Apply sqlx migrations to $DATABASE_URL
db-migrate:
    cd backend && sqlx migrate run

# Refresh .sqlx offline query cache
db-prepare:
    cargo sqlx prepare --workspace

# ─── Docker ─────────────────────────────────────────────────────────────────

# Build backend + frontend images
docker-build:
    docker compose build

# Start all services (postgres, backend, frontend)
up:
    docker compose up -d

# Stop and remove containers
down:
    docker compose down

# Tail logs from all services
logs:
    docker compose logs -f

# Start dev stack (postgres + backend + frontend with hot reload)
dev:
    docker compose --profile dev up -d postgres backend frontend-dev

# ─── Deploy ─────────────────────────────────────────────────────────────────

# Build images locally and push to remote host via SSH
deploy-docker: docker-build
    docker save amirsalarsafaeicom-backend:local amirsalarsafaeicom-frontend:local \
        | gzip \
        | ssh finRoot "gunzip | docker load"

# Sync source tree to VPS for in-place builds
deploy-rsync:
    rsync -avzP \
        --exclude='.git/' --exclude='.direnv/' --exclude='.devbox/' \
        --exclude='frontend/node_modules' --exclude='frontend/.next' \
        --exclude='backend/target' --exclude='target/' \
        --exclude='node_modules/' --exclude='backend/uploads' \
        . finRoot:/root/amirsalarsafaei.com/
