.PHONY: buf-generate clean

create-output-dirs:
	@mkdir -p autogenerated/ts
	@mkdir -p autogenerated/rust/src

buf-generate: clean create-output-dirs
	@buf generate

clean:
	@rm -rf autogenerated/ts
	@rm -rf autogenerated/rust

buf-lint:
	@buf lint

buf-breaking:
	@buf breaking --against '.git#branch=main'

buf-gen-ts: clean
	@mkdir -p autogenerated/ts
	@buf generate --template buf.gen.yaml --path proto --include-imports

buf-gen-rust: clean
	@mkdir -p autogenerated/rust
	@buf generate --template buf.gen.yaml --path proto --include-imports
create-output-dir:
	@mkdir -p autogenerated/ts

deploy:
	@rsync -avzP --exclude='.git/' --exclude='.direnv/' --exclude 'frontend/node_modules' --exclude 'frontend/.next' --exclude 'backend/target' --exclude 'target/' --exclude 'node_modules/' --exclude 'backend/uploads' . finRoot:/root/amirsalarsafaei.com/

docker-build:
	@docker compose build

docker-up:
	@docker compose up -d

docker-down:
	@docker compose down

docker-deploy: docker-build
	@docker save amirsalarsafaeicom-backend:latest amirsalarsafaeicom-frontend:latest | gzip | ssh finRoot "gunzip | docker load"

docker-compose-deploy: docker-build
	@docker compose up -d --no-deps backend frontend

