// Package rpc wraps the gRPC clients that talk to the amirsalarsafaei.com
// backend — the exact same services the website consumes over gRPC-Web.
package rpc

import (
	"context"
	"crypto/tls"
	"time"

	blogspb "github.com/amirsalarsafaei/amirsalarsafaei.com/autogenerated/go/blogs"
	playgroundpb "github.com/amirsalarsafaei/amirsalarsafaei.com/autogenerated/go/playground"
	profilepb "github.com/amirsalarsafaei/amirsalarsafaei.com/autogenerated/go/profile"
	"google.golang.org/grpc"
	"google.golang.org/grpc/credentials"
	"google.golang.org/grpc/credentials/insecure"
)

// Client bundles the backend service clients behind a single dial.
type Client struct {
	conn    *grpc.ClientConn
	Blogs   blogspb.BlogsClient
	Spotify playgroundpb.SpotifyClient
	Profile profilepb.ProfileClient
}

// Dial connects to the backend gRPC endpoint. When useTLS is true a standard
// TLS transport is used (e.g. for grpc.amirsalarsafaei.com:443); otherwise the
// connection is plaintext h2c (e.g. backend:8000 inside docker compose).
func Dial(addr string, useTLS bool) (*Client, error) {
	var creds credentials.TransportCredentials
	if useTLS {
		creds = credentials.NewTLS(&tls.Config{MinVersion: tls.VersionTLS12})
	} else {
		creds = insecure.NewCredentials()
	}

	conn, err := grpc.NewClient(addr, grpc.WithTransportCredentials(creds))
	if err != nil {
		return nil, err
	}

	return &Client{
		conn:    conn,
		Blogs:   blogspb.NewBlogsClient(conn),
		Spotify: playgroundpb.NewSpotifyClient(conn),
		Profile: profilepb.NewProfileClient(conn),
	}, nil
}

// Close tears down the underlying connection.
func (c *Client) Close() error { return c.conn.Close() }

// ListPublishedBlogs fetches a page of published blogs.
func (c *Client) ListPublishedBlogs(ctx context.Context, pageSize int32) ([]*blogspb.Blog, error) {
	ctx, cancel := context.WithTimeout(ctx, 10*time.Second)
	defer cancel()

	resp, err := c.Blogs.ListPublishedBlogs(ctx, &blogspb.ListPublishedBlogsRequest{
		PageSize: pageSize,
	})
	if err != nil {
		return nil, err
	}
	return resp.GetBlogs(), nil
}

// GetBlog fetches a single blog by id (the same RPC the blog detail page uses).
func (c *Client) GetBlog(ctx context.Context, id string) (*blogspb.Blog, error) {
	ctx, cancel := context.WithTimeout(ctx, 10*time.Second)
	defer cancel()

	resp, err := c.Blogs.GetBlog(ctx, &blogspb.GetBlogRequest{Id: id})
	if err != nil {
		return nil, err
	}
	return resp.GetBlog(), nil
}

// GetProfile fetches the shared "about me" profile (the same RPC the website's
// aboutme page uses).
func (c *Client) GetProfile(ctx context.Context) (*profilepb.GetProfileResponse, error) {
	ctx, cancel := context.WithTimeout(ctx, 10*time.Second)
	defer cancel()

	return c.Profile.GetProfile(ctx, &profilepb.GetProfileRequest{})
}

// SongStream is a server-stream of now-playing updates.
type SongStream = playgroundpb.Spotify_StreamRecentlyPlayedSongClient

// StreamRecentlyPlayed subscribes to live now-playing updates. The backend
// pushes the current track immediately and then on every change, so the caller
// never polls. The stream stays open for the lifetime of ctx (e.g. the SSH
// session).
func (c *Client) StreamRecentlyPlayed(ctx context.Context) (SongStream, error) {
	return c.Spotify.StreamRecentlyPlayedSong(ctx, &playgroundpb.GetRecentlyPlayedSongRequest{})
}
