import BlogContent from "./BlogContent";
import {
  GetBlogRequest,
  ListPublishedBlogsRequest,
} from "@amirsalarsafaei/autogenerated/blogs/blogs";
import { createGrpcClients } from "@/clients/grpc";

// Pre-render every published blog at build time against the live backend and
// refresh in the background (ISR). dynamicParams=true lets blogs published
// after the build still render on first request instead of 404ing.
export const revalidate = 300;
export const dynamicParams = true;

export { generateMetadata } from "./page.metadata";

export async function generateStaticParams(): Promise<{ id: string }[]> {
  // No backend during pure/offline Nix builds: pre-render nothing and let every
  // blog be generated on demand (dynamicParams=true). The on-server build runs
  // against the live backend and pre-renders the real set.
  if (process.env.NEXT_BUILD_SKIP_BACKEND === "1") {
    return [];
  }

  const { blogs_client } = createGrpcClients();

  const params: { id: string }[] = [];
  let pageToken = "";

  do {
    const res = await blogs_client.ListPublishedBlogs(
      ListPublishedBlogsRequest.create({ pageSize: 100, pageToken }),
    );
    params.push(...res.blogs.map((blog) => ({ id: blog.id })));
    pageToken = res.nextPageToken;
  } while (pageToken);

  return params;
}

export default async function BlogPage({ params }: { params: { id: string } }) {
  const { blogs_client } = createGrpcClients();
  const req = GetBlogRequest.create({ id: params.id });
  const data = await blogs_client.GetBlog(req);

  return <BlogContent initialData={data} />;
}
