package ui

import (
	"context"
	"fmt"
	"strings"

	tea "charm.land/bubbletea/v2"
	"charm.land/lipgloss/v2"
	blogspb "github.com/amirsalarsafaei/amirsalarsafaei.com/autogenerated/go/blogs"
)

type blogItem struct {
	id          string
	title       string
	content     string
	tags        []string
	publishedAt string
}

type blogsLoadedMsg struct {
	blogs []blogItem
	err   error
}

// loadBlogs calls Blogs.ListPublishedBlogs — the same RPC the website's blog
// index page uses.
func (m Model) loadBlogs() tea.Cmd {
	client := m.client
	return func() tea.Msg {
		blogs, err := client.ListPublishedBlogs(context.Background(), 20)
		if err != nil {
			return blogsLoadedMsg{err: err}
		}
		items := make([]blogItem, 0, len(blogs))
		for _, b := range blogs {
			items = append(items, toBlogItem(b))
		}
		return blogsLoadedMsg{blogs: items}
	}
}

func toBlogItem(b *blogspb.Blog) blogItem {
	tags := make([]string, 0, len(b.GetTags()))
	for _, t := range b.GetTags() {
		tags = append(tags, t.GetName())
	}
	published := ""
	if ts := b.GetPublishedAt(); ts != nil {
		published = ts.AsTime().Format("Jan 2, 2006")
	}
	return blogItem{
		id:          b.GetId(),
		title:       b.GetTitle(),
		content:     b.GetContent(),
		tags:        tags,
		publishedAt: published,
	}
}

func (m Model) updateBlogList(msg tea.KeyPressMsg) (tea.Model, tea.Cmd) {
	if len(m.blogs) == 0 {
		return m, nil
	}
	switch msg.String() {
	case "up", "k":
		if m.blogIdx > 0 {
			m.blogIdx--
		}
	case "down", "j":
		if m.blogIdx < len(m.blogs)-1 {
			m.blogIdx++
		}
	case "enter", "right", "l":
		m.view = viewBlogRead
		m.showMarkdown(m.blogMarkdown(m.blogs[m.blogIdx]))
	}
	return m, nil
}

func (m Model) blogMarkdown(b blogItem) string {
	var sb strings.Builder
	sb.WriteString("# " + b.title + "\n\n")
	meta := []string{}
	if b.publishedAt != "" {
		meta = append(meta, b.publishedAt)
	}
	if len(b.tags) > 0 {
		meta = append(meta, strings.Join(b.tags, ", "))
	}
	if len(meta) > 0 {
		sb.WriteString("_" + strings.Join(meta, " · ") + "_\n\n")
	}
	sb.WriteString("---\n\n")
	sb.WriteString(b.content)
	return sb.String()
}

func (m Model) blogListView() string {
	if !m.blogsLoaded {
		return m.styles.Spinner.Render(m.spinner.View()) + " fetching posts over gRPC…"
	}
	if m.blogsErr != nil {
		return m.styles.Err.Render("Failed to load blogs: " + m.blogsErr.Error())
	}
	if len(m.blogs) == 0 {
		return m.styles.Subtitle.Render("No published posts yet — check back soon.")
	}

	var rows []string
	for i, b := range m.blogs {
		bullet := "  "
		title := b.title
		if i == m.blogIdx {
			bullet = m.styles.BlogItemSelected.Render("▸ ")
			title = m.styles.BlogItemSelected.Render(title)
		} else {
			title = m.styles.BlogItem.Render(title)
		}

		meta := []string{}
		if b.publishedAt != "" {
			meta = append(meta, b.publishedAt)
		}
		for _, t := range b.tags {
			meta = append(meta, m.styles.Tag.Render(t))
		}
		metaLine := ""
		if len(meta) > 0 {
			metaLine = "\n    " + m.styles.BlogMeta.Render(strings.Join(meta, " "))
		}
		rows = append(rows, fmt.Sprintf("%s%s%s", bullet, title, metaLine))
	}
	return lipgloss.JoinVertical(lipgloss.Left, rows...)
}
