// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.8
//   protoc               unknown
// source: profile/profile.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import { grpc } from "@improbable-eng/grpc-web";
import { BrowserHeaders } from "browser-headers";

export const protobufPackage = "profile";

export interface GetProfileRequest {
}

export interface Link {
  label: string;
  url: string;
}

export interface GetProfileResponse {
  name: string;
  title: string;
  /** Bio rendered as Markdown. */
  bio: string;
  links: Link[];
  /** The skills shown as an `ls -la skills/` listing on the website. */
  skills: Skill[];
  /** "Current focus" rendered as Markdown. */
  currentFocus: string;
  /** Structured CV, one ResumeSection per CV heading. */
  resume?:
    | Resume
    | undefined;
  /**
   * Absolute URL of the profile photo, shown in the "about me" of every client
   * (rendered as half-blocks in the SSH terminal, an <img> on the website).
   */
  imageUrl: string;
}

/** A single skill/interest with a proficiency level. */
export interface Skill {
  /** e.g. "golang" */
  name: string;
  level: Skill_Level;
}

export enum Skill_Level {
  LEVEL_UNSPECIFIED = "LEVEL_UNSPECIFIED",
  EXPERT = "EXPERT",
  PROFICIENT = "PROFICIENT",
  LEARNING = "LEARNING",
  PASSION = "PASSION",
  UNRECOGNIZED = "UNRECOGNIZED",
}

export function skill_LevelFromJSON(object: any): Skill_Level {
  switch (object) {
    case 0:
    case "LEVEL_UNSPECIFIED":
      return Skill_Level.LEVEL_UNSPECIFIED;
    case 1:
    case "EXPERT":
      return Skill_Level.EXPERT;
    case 2:
    case "PROFICIENT":
      return Skill_Level.PROFICIENT;
    case 3:
    case "LEARNING":
      return Skill_Level.LEARNING;
    case 4:
    case "PASSION":
      return Skill_Level.PASSION;
    case -1:
    case "UNRECOGNIZED":
    default:
      return Skill_Level.UNRECOGNIZED;
  }
}

export function skill_LevelToJSON(object: Skill_Level): string {
  switch (object) {
    case Skill_Level.LEVEL_UNSPECIFIED:
      return "LEVEL_UNSPECIFIED";
    case Skill_Level.EXPERT:
      return "EXPERT";
    case Skill_Level.PROFICIENT:
      return "PROFICIENT";
    case Skill_Level.LEARNING:
      return "LEARNING";
    case Skill_Level.PASSION:
      return "PASSION";
    case Skill_Level.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

export function skill_LevelToNumber(object: Skill_Level): number {
  switch (object) {
    case Skill_Level.LEVEL_UNSPECIFIED:
      return 0;
    case Skill_Level.EXPERT:
      return 1;
    case Skill_Level.PROFICIENT:
      return 2;
    case Skill_Level.LEARNING:
      return 3;
    case Skill_Level.PASSION:
      return 4;
    case Skill_Level.UNRECOGNIZED:
    default:
      return -1;
  }
}

/** Structured CV shared by every client. */
export interface Resume {
  fullName: string;
  email: string;
  githubUrl: string;
  sections: ResumeSection[];
}

export interface ResumeSection {
  /** e.g. "Education" */
  heading: string;
  /** preformatted text block */
  body: string;
}

function createBaseGetProfileRequest(): GetProfileRequest {
  return {};
}

export const GetProfileRequest: MessageFns<GetProfileRequest> = {
  encode(_: GetProfileRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetProfileRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetProfileRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(_: any): GetProfileRequest {
    return {};
  },

  toJSON(_: GetProfileRequest): unknown {
    const obj: any = {};
    return obj;
  },

  create<I extends Exact<DeepPartial<GetProfileRequest>, I>>(base?: I): GetProfileRequest {
    return GetProfileRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GetProfileRequest>, I>>(_: I): GetProfileRequest {
    const message = createBaseGetProfileRequest();
    return message;
  },
};

function createBaseLink(): Link {
  return { label: "", url: "" };
}

export const Link: MessageFns<Link> = {
  encode(message: Link, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.label !== "") {
      writer.uint32(10).string(message.label);
    }
    if (message.url !== "") {
      writer.uint32(18).string(message.url);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Link {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseLink();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.label = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.url = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Link {
    return {
      label: isSet(object.label) ? globalThis.String(object.label) : "",
      url: isSet(object.url) ? globalThis.String(object.url) : "",
    };
  },

  toJSON(message: Link): unknown {
    const obj: any = {};
    if (message.label !== "") {
      obj.label = message.label;
    }
    if (message.url !== "") {
      obj.url = message.url;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Link>, I>>(base?: I): Link {
    return Link.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Link>, I>>(object: I): Link {
    const message = createBaseLink();
    message.label = object.label ?? "";
    message.url = object.url ?? "";
    return message;
  },
};

function createBaseGetProfileResponse(): GetProfileResponse {
  return { name: "", title: "", bio: "", links: [], skills: [], currentFocus: "", resume: undefined, imageUrl: "" };
}

export const GetProfileResponse: MessageFns<GetProfileResponse> = {
  encode(message: GetProfileResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.name !== "") {
      writer.uint32(10).string(message.name);
    }
    if (message.title !== "") {
      writer.uint32(18).string(message.title);
    }
    if (message.bio !== "") {
      writer.uint32(26).string(message.bio);
    }
    for (const v of message.links) {
      Link.encode(v!, writer.uint32(34).fork()).join();
    }
    for (const v of message.skills) {
      Skill.encode(v!, writer.uint32(42).fork()).join();
    }
    if (message.currentFocus !== "") {
      writer.uint32(50).string(message.currentFocus);
    }
    if (message.resume !== undefined) {
      Resume.encode(message.resume, writer.uint32(58).fork()).join();
    }
    if (message.imageUrl !== "") {
      writer.uint32(66).string(message.imageUrl);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetProfileResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetProfileResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.name = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.title = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.bio = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.links.push(Link.decode(reader, reader.uint32()));
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.skills.push(Skill.decode(reader, reader.uint32()));
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.currentFocus = reader.string();
          continue;
        }
        case 7: {
          if (tag !== 58) {
            break;
          }

          message.resume = Resume.decode(reader, reader.uint32());
          continue;
        }
        case 8: {
          if (tag !== 66) {
            break;
          }

          message.imageUrl = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): GetProfileResponse {
    return {
      name: isSet(object.name) ? globalThis.String(object.name) : "",
      title: isSet(object.title) ? globalThis.String(object.title) : "",
      bio: isSet(object.bio) ? globalThis.String(object.bio) : "",
      links: globalThis.Array.isArray(object?.links) ? object.links.map((e: any) => Link.fromJSON(e)) : [],
      skills: globalThis.Array.isArray(object?.skills) ? object.skills.map((e: any) => Skill.fromJSON(e)) : [],
      currentFocus: isSet(object.currentFocus)
        ? globalThis.String(object.currentFocus)
        : isSet(object.current_focus)
        ? globalThis.String(object.current_focus)
        : "",
      resume: isSet(object.resume) ? Resume.fromJSON(object.resume) : undefined,
      imageUrl: isSet(object.imageUrl)
        ? globalThis.String(object.imageUrl)
        : isSet(object.image_url)
        ? globalThis.String(object.image_url)
        : "",
    };
  },

  toJSON(message: GetProfileResponse): unknown {
    const obj: any = {};
    if (message.name !== "") {
      obj.name = message.name;
    }
    if (message.title !== "") {
      obj.title = message.title;
    }
    if (message.bio !== "") {
      obj.bio = message.bio;
    }
    if (message.links?.length) {
      obj.links = message.links.map((e) => Link.toJSON(e));
    }
    if (message.skills?.length) {
      obj.skills = message.skills.map((e) => Skill.toJSON(e));
    }
    if (message.currentFocus !== "") {
      obj.currentFocus = message.currentFocus;
    }
    if (message.resume !== undefined) {
      obj.resume = Resume.toJSON(message.resume);
    }
    if (message.imageUrl !== "") {
      obj.imageUrl = message.imageUrl;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<GetProfileResponse>, I>>(base?: I): GetProfileResponse {
    return GetProfileResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GetProfileResponse>, I>>(object: I): GetProfileResponse {
    const message = createBaseGetProfileResponse();
    message.name = object.name ?? "";
    message.title = object.title ?? "";
    message.bio = object.bio ?? "";
    message.links = object.links?.map((e) => Link.fromPartial(e)) || [];
    message.skills = object.skills?.map((e) => Skill.fromPartial(e)) || [];
    message.currentFocus = object.currentFocus ?? "";
    message.resume = (object.resume !== undefined && object.resume !== null)
      ? Resume.fromPartial(object.resume)
      : undefined;
    message.imageUrl = object.imageUrl ?? "";
    return message;
  },
};

function createBaseSkill(): Skill {
  return { name: "", level: Skill_Level.LEVEL_UNSPECIFIED };
}

export const Skill: MessageFns<Skill> = {
  encode(message: Skill, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.name !== "") {
      writer.uint32(10).string(message.name);
    }
    if (message.level !== Skill_Level.LEVEL_UNSPECIFIED) {
      writer.uint32(16).int32(skill_LevelToNumber(message.level));
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Skill {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseSkill();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.name = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.level = skill_LevelFromJSON(reader.int32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Skill {
    return {
      name: isSet(object.name) ? globalThis.String(object.name) : "",
      level: isSet(object.level) ? skill_LevelFromJSON(object.level) : Skill_Level.LEVEL_UNSPECIFIED,
    };
  },

  toJSON(message: Skill): unknown {
    const obj: any = {};
    if (message.name !== "") {
      obj.name = message.name;
    }
    if (message.level !== Skill_Level.LEVEL_UNSPECIFIED) {
      obj.level = skill_LevelToJSON(message.level);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Skill>, I>>(base?: I): Skill {
    return Skill.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Skill>, I>>(object: I): Skill {
    const message = createBaseSkill();
    message.name = object.name ?? "";
    message.level = object.level ?? Skill_Level.LEVEL_UNSPECIFIED;
    return message;
  },
};

function createBaseResume(): Resume {
  return { fullName: "", email: "", githubUrl: "", sections: [] };
}

export const Resume: MessageFns<Resume> = {
  encode(message: Resume, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.fullName !== "") {
      writer.uint32(10).string(message.fullName);
    }
    if (message.email !== "") {
      writer.uint32(18).string(message.email);
    }
    if (message.githubUrl !== "") {
      writer.uint32(26).string(message.githubUrl);
    }
    for (const v of message.sections) {
      ResumeSection.encode(v!, writer.uint32(34).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Resume {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseResume();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.fullName = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.email = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.githubUrl = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.sections.push(ResumeSection.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Resume {
    return {
      fullName: isSet(object.fullName)
        ? globalThis.String(object.fullName)
        : isSet(object.full_name)
        ? globalThis.String(object.full_name)
        : "",
      email: isSet(object.email) ? globalThis.String(object.email) : "",
      githubUrl: isSet(object.githubUrl)
        ? globalThis.String(object.githubUrl)
        : isSet(object.github_url)
        ? globalThis.String(object.github_url)
        : "",
      sections: globalThis.Array.isArray(object?.sections)
        ? object.sections.map((e: any) => ResumeSection.fromJSON(e))
        : [],
    };
  },

  toJSON(message: Resume): unknown {
    const obj: any = {};
    if (message.fullName !== "") {
      obj.fullName = message.fullName;
    }
    if (message.email !== "") {
      obj.email = message.email;
    }
    if (message.githubUrl !== "") {
      obj.githubUrl = message.githubUrl;
    }
    if (message.sections?.length) {
      obj.sections = message.sections.map((e) => ResumeSection.toJSON(e));
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Resume>, I>>(base?: I): Resume {
    return Resume.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Resume>, I>>(object: I): Resume {
    const message = createBaseResume();
    message.fullName = object.fullName ?? "";
    message.email = object.email ?? "";
    message.githubUrl = object.githubUrl ?? "";
    message.sections = object.sections?.map((e) => ResumeSection.fromPartial(e)) || [];
    return message;
  },
};

function createBaseResumeSection(): ResumeSection {
  return { heading: "", body: "" };
}

export const ResumeSection: MessageFns<ResumeSection> = {
  encode(message: ResumeSection, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.heading !== "") {
      writer.uint32(10).string(message.heading);
    }
    if (message.body !== "") {
      writer.uint32(18).string(message.body);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ResumeSection {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseResumeSection();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.heading = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.body = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ResumeSection {
    return {
      heading: isSet(object.heading) ? globalThis.String(object.heading) : "",
      body: isSet(object.body) ? globalThis.String(object.body) : "",
    };
  },

  toJSON(message: ResumeSection): unknown {
    const obj: any = {};
    if (message.heading !== "") {
      obj.heading = message.heading;
    }
    if (message.body !== "") {
      obj.body = message.body;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ResumeSection>, I>>(base?: I): ResumeSection {
    return ResumeSection.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ResumeSection>, I>>(object: I): ResumeSection {
    const message = createBaseResumeSection();
    message.heading = object.heading ?? "";
    message.body = object.body ?? "";
    return message;
  },
};

/**
 * Profile exposes the "about me" content that is shared by every client
 * (website + SSH terminal) so it has a single source of truth in the backend.
 */
export interface Profile {
  GetProfile(request: DeepPartial<GetProfileRequest>, metadata?: grpc.Metadata): Promise<GetProfileResponse>;
}

export class ProfileClientImpl implements Profile {
  private readonly rpc: Rpc;

  constructor(rpc: Rpc) {
    this.rpc = rpc;
    this.GetProfile = this.GetProfile.bind(this);
  }

  GetProfile(request: DeepPartial<GetProfileRequest>, metadata?: grpc.Metadata): Promise<GetProfileResponse> {
    return this.rpc.unary(ProfileGetProfileDesc, GetProfileRequest.fromPartial(request), metadata);
  }
}

export const ProfileDesc = { serviceName: "profile.Profile" };

export const ProfileGetProfileDesc: UnaryMethodDefinitionish = {
  methodName: "GetProfile",
  service: ProfileDesc,
  requestStream: false,
  responseStream: false,
  requestType: {
    serializeBinary() {
      return GetProfileRequest.encode(this).finish();
    },
  } as any,
  responseType: {
    deserializeBinary(data: Uint8Array) {
      const value = GetProfileResponse.decode(data);
      return {
        ...value,
        toObject() {
          return value;
        },
      };
    },
  } as any,
};

interface UnaryMethodDefinitionishR extends grpc.UnaryMethodDefinition<any, any> {
  requestStream: any;
  responseStream: any;
}

type UnaryMethodDefinitionish = UnaryMethodDefinitionishR;

interface Rpc {
  unary<T extends UnaryMethodDefinitionish>(
    methodDesc: T,
    request: any,
    metadata: grpc.Metadata | undefined,
  ): Promise<any>;
}

export class GrpcWebImpl {
  private host: string;
  private options: {
    transport?: grpc.TransportFactory;

    debug?: boolean;
    metadata?: grpc.Metadata;
    upStreamRetryCodes?: number[];
  };

  constructor(
    host: string,
    options: {
      transport?: grpc.TransportFactory;

      debug?: boolean;
      metadata?: grpc.Metadata;
      upStreamRetryCodes?: number[];
    },
  ) {
    this.host = host;
    this.options = options;
  }

  unary<T extends UnaryMethodDefinitionish>(
    methodDesc: T,
    _request: any,
    metadata: grpc.Metadata | undefined,
  ): Promise<any> {
    const request = { ..._request, ...methodDesc.requestType };
    const maybeCombinedMetadata = metadata && this.options.metadata
      ? new BrowserHeaders({ ...this.options?.metadata.headersMap, ...metadata?.headersMap })
      : metadata ?? this.options.metadata;
    return new Promise((resolve, reject) => {
      grpc.unary(methodDesc, {
        request,
        host: this.host,
        metadata: maybeCombinedMetadata ?? {},
        ...(this.options.transport !== undefined ? { transport: this.options.transport } : {}),
        debug: this.options.debug ?? false,
        onEnd: function (response) {
          if (response.status === grpc.Code.OK) {
            resolve(response.message!.toObject());
          } else {
            const err = new GrpcWebError(response.statusMessage, response.status, response.trailers);
            reject(err);
          }
        },
      });
    });
  }
}

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export class GrpcWebError extends globalThis.Error {
  constructor(message: string, public code: grpc.Code, public metadata: grpc.Metadata) {
    super(message);
  }
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
