/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/gadget-music.glb -T -k -t -o src/modules/playground/models/GadgetMusic.tsx 
Files: public/gadget-music.glb [5.56MB] > /home/amirsalar/personal/amirsalarsafaei.com/src/modules/playground/models/gadget-music-transformed.glb [511.46KB] (91%)
*/

import * as THREE from 'three'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    gadget001_low_gadget_0: THREE.Mesh
  }
  materials: {
    gadget: THREE.MeshStandardMaterial
  }
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/gadget-music-transformed.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh name="gadget001_low_gadget_0" geometry={nodes.gadget001_low_gadget_0.geometry} material={materials.gadget} rotation={[-1.562, 0, 0]} scale={0.064} />
    </group>
  )
}

useGLTF.preload('/gadget-music-transformed.glb')
