// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: profile/profile.proto

package profile

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Skill_Level int32

const (
	Skill_LEVEL_UNSPECIFIED Skill_Level = 0
	Skill_EXPERT            Skill_Level = 1
	Skill_PROFICIENT        Skill_Level = 2
	Skill_LEARNING          Skill_Level = 3
	Skill_PASSION           Skill_Level = 4
)

// Enum value maps for Skill_Level.
var (
	Skill_Level_name = map[int32]string{
		0: "LEVEL_UNSPECIFIED",
		1: "EXPERT",
		2: "PROFICIENT",
		3: "LEARNING",
		4: "PASSION",
	}
	Skill_Level_value = map[string]int32{
		"LEVEL_UNSPECIFIED": 0,
		"EXPERT":            1,
		"PROFICIENT":        2,
		"LEARNING":          3,
		"PASSION":           4,
	}
)

func (x Skill_Level) Enum() *Skill_Level {
	p := new(Skill_Level)
	*p = x
	return p
}

func (x Skill_Level) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Skill_Level) Descriptor() protoreflect.EnumDescriptor {
	return file_profile_profile_proto_enumTypes[0].Descriptor()
}

func (Skill_Level) Type() protoreflect.EnumType {
	return &file_profile_profile_proto_enumTypes[0]
}

func (x Skill_Level) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Skill_Level.Descriptor instead.
func (Skill_Level) EnumDescriptor() ([]byte, []int) {
	return file_profile_profile_proto_rawDescGZIP(), []int{3, 0}
}

type GetProfileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProfileRequest) Reset() {
	*x = GetProfileRequest{}
	mi := &file_profile_profile_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProfileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProfileRequest) ProtoMessage() {}

func (x *GetProfileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_profile_profile_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProfileRequest.ProtoReflect.Descriptor instead.
func (*GetProfileRequest) Descriptor() ([]byte, []int) {
	return file_profile_profile_proto_rawDescGZIP(), []int{0}
}

type Link struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Label         string                 `protobuf:"bytes,1,opt,name=label,proto3" json:"label,omitempty"`
	Url           string                 `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Link) Reset() {
	*x = Link{}
	mi := &file_profile_profile_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Link) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Link) ProtoMessage() {}

func (x *Link) ProtoReflect() protoreflect.Message {
	mi := &file_profile_profile_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Link.ProtoReflect.Descriptor instead.
func (*Link) Descriptor() ([]byte, []int) {
	return file_profile_profile_proto_rawDescGZIP(), []int{1}
}

func (x *Link) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *Link) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

type GetProfileResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Name  string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Title string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	// Bio rendered as Markdown.
	Bio   string  `protobuf:"bytes,3,opt,name=bio,proto3" json:"bio,omitempty"`
	Links []*Link `protobuf:"bytes,4,rep,name=links,proto3" json:"links,omitempty"`
	// The skills shown as an `ls -la skills/` listing on the website.
	Skills []*Skill `protobuf:"bytes,5,rep,name=skills,proto3" json:"skills,omitempty"`
	// "Current focus" rendered as Markdown.
	CurrentFocus string `protobuf:"bytes,6,opt,name=current_focus,json=currentFocus,proto3" json:"current_focus,omitempty"`
	// Structured CV, one ResumeSection per CV heading.
	Resume *Resume `protobuf:"bytes,7,opt,name=resume,proto3" json:"resume,omitempty"`
	// Absolute URL of the profile photo, shown in the "about me" of every client
	// (rendered as half-blocks in the SSH terminal, an <img> on the website).
	ImageUrl      string `protobuf:"bytes,8,opt,name=image_url,json=imageUrl,proto3" json:"image_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProfileResponse) Reset() {
	*x = GetProfileResponse{}
	mi := &file_profile_profile_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProfileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProfileResponse) ProtoMessage() {}

func (x *GetProfileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_profile_profile_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProfileResponse.ProtoReflect.Descriptor instead.
func (*GetProfileResponse) Descriptor() ([]byte, []int) {
	return file_profile_profile_proto_rawDescGZIP(), []int{2}
}

func (x *GetProfileResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GetProfileResponse) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *GetProfileResponse) GetBio() string {
	if x != nil {
		return x.Bio
	}
	return ""
}

func (x *GetProfileResponse) GetLinks() []*Link {
	if x != nil {
		return x.Links
	}
	return nil
}

func (x *GetProfileResponse) GetSkills() []*Skill {
	if x != nil {
		return x.Skills
	}
	return nil
}

func (x *GetProfileResponse) GetCurrentFocus() string {
	if x != nil {
		return x.CurrentFocus
	}
	return ""
}

func (x *GetProfileResponse) GetResume() *Resume {
	if x != nil {
		return x.Resume
	}
	return nil
}

func (x *GetProfileResponse) GetImageUrl() string {
	if x != nil {
		return x.ImageUrl
	}
	return ""
}

// A single skill/interest with a proficiency level.
type Skill struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"` // e.g. "golang"
	Level         Skill_Level            `protobuf:"varint,2,opt,name=level,proto3,enum=profile.Skill_Level" json:"level,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Skill) Reset() {
	*x = Skill{}
	mi := &file_profile_profile_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Skill) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Skill) ProtoMessage() {}

func (x *Skill) ProtoReflect() protoreflect.Message {
	mi := &file_profile_profile_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Skill.ProtoReflect.Descriptor instead.
func (*Skill) Descriptor() ([]byte, []int) {
	return file_profile_profile_proto_rawDescGZIP(), []int{3}
}

func (x *Skill) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Skill) GetLevel() Skill_Level {
	if x != nil {
		return x.Level
	}
	return Skill_LEVEL_UNSPECIFIED
}

// Structured CV shared by every client.
type Resume struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FullName      string                 `protobuf:"bytes,1,opt,name=full_name,json=fullName,proto3" json:"full_name,omitempty"`
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	GithubUrl     string                 `protobuf:"bytes,3,opt,name=github_url,json=githubUrl,proto3" json:"github_url,omitempty"`
	Sections      []*ResumeSection       `protobuf:"bytes,4,rep,name=sections,proto3" json:"sections,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Resume) Reset() {
	*x = Resume{}
	mi := &file_profile_profile_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Resume) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Resume) ProtoMessage() {}

func (x *Resume) ProtoReflect() protoreflect.Message {
	mi := &file_profile_profile_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Resume.ProtoReflect.Descriptor instead.
func (*Resume) Descriptor() ([]byte, []int) {
	return file_profile_profile_proto_rawDescGZIP(), []int{4}
}

func (x *Resume) GetFullName() string {
	if x != nil {
		return x.FullName
	}
	return ""
}

func (x *Resume) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *Resume) GetGithubUrl() string {
	if x != nil {
		return x.GithubUrl
	}
	return ""
}

func (x *Resume) GetSections() []*ResumeSection {
	if x != nil {
		return x.Sections
	}
	return nil
}

type ResumeSection struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Heading       string                 `protobuf:"bytes,1,opt,name=heading,proto3" json:"heading,omitempty"` // e.g. "Education"
	Body          string                 `protobuf:"bytes,2,opt,name=body,proto3" json:"body,omitempty"`       // preformatted text block
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResumeSection) Reset() {
	*x = ResumeSection{}
	mi := &file_profile_profile_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResumeSection) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResumeSection) ProtoMessage() {}

func (x *ResumeSection) ProtoReflect() protoreflect.Message {
	mi := &file_profile_profile_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResumeSection.ProtoReflect.Descriptor instead.
func (*ResumeSection) Descriptor() ([]byte, []int) {
	return file_profile_profile_proto_rawDescGZIP(), []int{5}
}

func (x *ResumeSection) GetHeading() string {
	if x != nil {
		return x.Heading
	}
	return ""
}

func (x *ResumeSection) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

var File_profile_profile_proto protoreflect.FileDescriptor

const file_profile_profile_proto_rawDesc = "" +
	"\n" +
	"\x15profile/profile.proto\x12\aprofile\"\x13\n" +
	"\x11GetProfileRequest\".\n" +
	"\x04Link\x12\x14\n" +
	"\x05label\x18\x01 \x01(\tR\x05label\x12\x10\n" +
	"\x03url\x18\x02 \x01(\tR\x03url\"\x88\x02\n" +
	"\x12GetProfileResponse\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x10\n" +
	"\x03bio\x18\x03 \x01(\tR\x03bio\x12#\n" +
	"\x05links\x18\x04 \x03(\v2\r.profile.LinkR\x05links\x12&\n" +
	"\x06skills\x18\x05 \x03(\v2\x0e.profile.SkillR\x06skills\x12#\n" +
	"\rcurrent_focus\x18\x06 \x01(\tR\fcurrentFocus\x12'\n" +
	"\x06resume\x18\a \x01(\v2\x0f.profile.ResumeR\x06resume\x12\x1b\n" +
	"\timage_url\x18\b \x01(\tR\bimageUrl\"\x9e\x01\n" +
	"\x05Skill\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12*\n" +
	"\x05level\x18\x02 \x01(\x0e2\x14.profile.Skill.LevelR\x05level\"U\n" +
	"\x05Level\x12\x15\n" +
	"\x11LEVEL_UNSPECIFIED\x10\x00\x12\n" +
	"\n" +
	"\x06EXPERT\x10\x01\x12\x0e\n" +
	"\n" +
	"PROFICIENT\x10\x02\x12\f\n" +
	"\bLEARNING\x10\x03\x12\v\n" +
	"\aPASSION\x10\x04\"\x8e\x01\n" +
	"\x06Resume\x12\x1b\n" +
	"\tfull_name\x18\x01 \x01(\tR\bfullName\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12\x1d\n" +
	"\n" +
	"github_url\x18\x03 \x01(\tR\tgithubUrl\x122\n" +
	"\bsections\x18\x04 \x03(\v2\x16.profile.ResumeSectionR\bsections\"=\n" +
	"\rResumeSection\x12\x18\n" +
	"\aheading\x18\x01 \x01(\tR\aheading\x12\x12\n" +
	"\x04body\x18\x02 \x01(\tR\x04body2P\n" +
	"\aProfile\x12E\n" +
	"\n" +
	"GetProfile\x12\x1a.profile.GetProfileRequest\x1a\x1b.profile.GetProfileResponseB\xa0\x01\n" +
	"\vcom.profileB\fProfileProtoP\x01ZGgithub.com/amirsalarsafaei/amirsalarsafaei.com/autogenerated/go/profile\xa2\x02\x03PXX\xaa\x02\aProfile\xca\x02\aProfile\xe2\x02\x13Profile\\GPBMetadata\xea\x02\aProfileb\x06proto3"

var (
	file_profile_profile_proto_rawDescOnce sync.Once
	file_profile_profile_proto_rawDescData []byte
)

func file_profile_profile_proto_rawDescGZIP() []byte {
	file_profile_profile_proto_rawDescOnce.Do(func() {
		file_profile_profile_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_profile_profile_proto_rawDesc), len(file_profile_profile_proto_rawDesc)))
	})
	return file_profile_profile_proto_rawDescData
}

var file_profile_profile_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_profile_profile_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_profile_profile_proto_goTypes = []any{
	(Skill_Level)(0),           // 0: profile.Skill.Level
	(*GetProfileRequest)(nil),  // 1: profile.GetProfileRequest
	(*Link)(nil),               // 2: profile.Link
	(*GetProfileResponse)(nil), // 3: profile.GetProfileResponse
	(*Skill)(nil),              // 4: profile.Skill
	(*Resume)(nil),             // 5: profile.Resume
	(*ResumeSection)(nil),      // 6: profile.ResumeSection
}
var file_profile_profile_proto_depIdxs = []int32{
	2, // 0: profile.GetProfileResponse.links:type_name -> profile.Link
	4, // 1: profile.GetProfileResponse.skills:type_name -> profile.Skill
	5, // 2: profile.GetProfileResponse.resume:type_name -> profile.Resume
	0, // 3: profile.Skill.level:type_name -> profile.Skill.Level
	6, // 4: profile.Resume.sections:type_name -> profile.ResumeSection
	1, // 5: profile.Profile.GetProfile:input_type -> profile.GetProfileRequest
	3, // 6: profile.Profile.GetProfile:output_type -> profile.GetProfileResponse
	6, // [6:7] is the sub-list for method output_type
	5, // [5:6] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_profile_profile_proto_init() }
func file_profile_profile_proto_init() {
	if File_profile_profile_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_profile_profile_proto_rawDesc), len(file_profile_profile_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_profile_profile_proto_goTypes,
		DependencyIndexes: file_profile_profile_proto_depIdxs,
		EnumInfos:         file_profile_profile_proto_enumTypes,
		MessageInfos:      file_profile_profile_proto_msgTypes,
	}.Build()
	File_profile_profile_proto = out.File
	file_profile_profile_proto_goTypes = nil
	file_profile_profile_proto_depIdxs = nil
}
