package ui

import (
	"context"
	"image"
	"strings"

	tea "charm.land/bubbletea/v2"

	profilepb "github.com/amirsalarsafaei/amirsalarsafaei.com/autogenerated/go/profile"
	"github.com/amirsalarsafaei/amirsalarsafaei.com/tuissh/internal/termimg"
)

// barWidth is the number of segments in a skill proficiency bar.
const barWidth = 5

type profileLink struct {
	label string
	url   string
}

type skill struct {
	name  string
	level string // lowercase label, e.g. "expert"
	score int    // filled segments out of barWidth, derived from the enum
}

type resumeSection struct {
	heading string
	body    string
}

type resumeInfo struct {
	fullName  string
	email     string
	githubURL string
	sections  []resumeSection
}

type profileInfo struct {
	name         string
	title        string
	bio          string // markdown
	currentFocus string // markdown
	skills       []skill
	resume       resumeInfo
	links        []profileLink
	imageURL     string // profile photo, shown atop the about page
}

type profileLoadedMsg struct {
	profile profileInfo
	err     error
}

// levelLabel/levelScore map the Skill.Level enum to its display label and the
// number of filled bar segments. "passion" denotes enthusiasm rather than
// mastery, so it sits between learning and proficient.
func levelLabel(l profilepb.Skill_Level) string {
	switch l {
	case profilepb.Skill_EXPERT:
		return "expert"
	case profilepb.Skill_PROFICIENT:
		return "proficient"
	case profilepb.Skill_PASSION:
		return "passion"
	case profilepb.Skill_LEARNING:
		return "learning"
	default:
		return ""
	}
}

func levelScore(l profilepb.Skill_Level) int {
	switch l {
	case profilepb.Skill_EXPERT:
		return 5
	case profilepb.Skill_PROFICIENT:
		return 4
	case profilepb.Skill_PASSION:
		return 3
	case profilepb.Skill_LEARNING:
		return 2
	default:
		return 0
	}
}

func mkSkill(name string, l profilepb.Skill_Level) skill {
	return skill{name: name, level: levelLabel(l), score: levelScore(l)}
}

// fallbackProfile is rendered only if the backend is unreachable, so the
// terminal still shows something useful.
var fallbackProfile = profileInfo{
	name:  "AmirSalar Safaei",
	title: "Software Engineer & System Architect",
	bio: "Hello! I'm a passionate software engineer. The backend was unreachable, " +
		"so this is a fallback bio — visit https://amirsalarsafaei.com for the real thing.",
	currentFocus: "Backend unreachable — current focus unavailable.",
	skills: []skill{
		mkSkill("golang", profilepb.Skill_EXPERT),
		mkSkill("python", profilepb.Skill_EXPERT),
		mkSkill("rust", profilepb.Skill_PROFICIENT),
		mkSkill("distributed-systems", profilepb.Skill_PASSION),
	},
	resume: resumeInfo{
		fullName:  "AmirSalar Safaei Ghaderi",
		email:     "amirsalarsafaeighaderi@gmail.com",
		githubURL: "https://github.com/amirsalarsafaei",
	},
	links: []profileLink{
		{label: "Website", url: "https://amirsalarsafaei.com"},
		{label: "GitHub", url: "https://github.com/amirsalarsafaei"},
		{label: "Email", url: "mailto:amirs.s.g.o@gmail.com"},
		{label: "Telegram", url: "https://t.me/amirsalarsafaei"},
		{label: "LinkedIn", url: "https://linkedin.com/in/amir-salar-safaei"},
	},
}

// loadProfile calls Profile.GetProfile — the same RPC the website's about page
// uses, so the bio/skills/resume/links have a single source of truth in the
// backend.
func (m Model) loadProfile() tea.Cmd {
	client := m.client
	return func() tea.Msg {
		resp, err := client.GetProfile(context.Background())
		if err != nil {
			return profileLoadedMsg{profile: fallbackProfile, err: err}
		}

		links := make([]profileLink, 0, len(resp.GetLinks()))
		for _, l := range resp.GetLinks() {
			links = append(links, profileLink{label: l.GetLabel(), url: l.GetUrl()})
		}

		skills := make([]skill, 0, len(resp.GetSkills()))
		for _, s := range resp.GetSkills() {
			skills = append(skills, mkSkill(s.GetName(), s.GetLevel()))
		}

		var resume resumeInfo
		if r := resp.GetResume(); r != nil {
			sections := make([]resumeSection, 0, len(r.GetSections()))
			for _, sec := range r.GetSections() {
				sections = append(sections, resumeSection{
					heading: sec.GetHeading(),
					body:    sec.GetBody(),
				})
			}
			resume = resumeInfo{
				fullName:  r.GetFullName(),
				email:     r.GetEmail(),
				githubURL: r.GetGithubUrl(),
				sections:  sections,
			}
		}

		return profileLoadedMsg{profile: profileInfo{
			name:         resp.GetName(),
			title:        resp.GetTitle(),
			bio:          resp.GetBio(),
			currentFocus: resp.GetCurrentFocus(),
			skills:       skills,
			resume:       resume,
			links:        links,
			imageURL:     resp.GetImageUrl(),
		}}
	}
}

// --- profile photo (about page) -------------------------------------------
//
// The photo is fetched from profile.image_url and rendered as Unicode
// half-blocks atop the about page — the same approach as the Spotify album art,
// so both clients (website + terminal) draw the same backend-served image.

const (
	profileImageMaxCols = 36
	profileImageMaxRows = 18
)

type profileImageMsg struct {
	url string
	img image.Image
	err error
}

// loadProfileImage downloads the profile photo named by profile.image_url.
func (m Model) loadProfileImage() tea.Cmd {
	url := m.profile.imageURL
	if url == "" {
		return nil
	}
	return func() tea.Msg {
		img, err := termimg.Fetch(context.Background(), url)
		return profileImageMsg{url: url, img: img, err: err}
	}
}

// renderProfileImage (re)renders the cached photo to the current width and
// colour profile. Cheap and idempotent — safe to call on resize or when the
// colour profile is learned.
func (m *Model) renderProfileImage() {
	if m.profileImg == nil {
		m.profileImgRendered = ""
		return
	}
	maxCols := min(profileImageMaxCols, max(m.contentWidth()/2, 8))
	b := m.profileImg.Bounds()
	cols, rows := termimg.FitBox(b.Dx(), b.Dy(), maxCols, profileImageMaxRows)
	if s, ok := termimg.Render(m.profileImg, cols, rows, m.colorful); ok {
		m.profileImgRendered = s
	} else {
		m.profileImgRendered = ""
	}
}

// skillBar renders a proficiency bar from the skill's score, e.g. "█████░".
func skillBar(s skill) string {
	filled := s.score
	if filled > barWidth {
		filled = barWidth
	}
	return strings.Repeat("█", filled) + strings.Repeat("░", barWidth-filled)
}

func aboutMarkdown(p profileInfo) string {
	var sb strings.Builder
	sb.WriteString("# " + p.name + "\n\n")
	sb.WriteString("**" + p.title + "**\n\n")
	sb.WriteString(p.bio)
	sb.WriteString("\n\n")

	if len(p.skills) > 0 {
		sb.WriteString("## Skills\n\n```\n")
		for _, s := range p.skills {
			// Pad the name so the bars line up.
			sb.WriteString(s.name)
			for i := len(s.name); i < 24; i++ {
				sb.WriteString(" ")
			}
			sb.WriteString(skillBar(s) + "  " + s.level + "\n")
		}
		sb.WriteString("```\n\n")
	}

	if p.currentFocus != "" {
		sb.WriteString(p.currentFocus)
		sb.WriteString("\n\n")
	}

	if len(p.resume.sections) > 0 {
		sb.WriteString("---\n\n# " + p.resume.fullName + "\n\n")
		sb.WriteString("`" + p.resume.email + "` · " + p.resume.githubURL + "\n\n")
		for _, sec := range p.resume.sections {
			sb.WriteString("## " + sec.heading + "\n\n```\n" + sec.body + "\n```\n\n")
		}
	}

	sb.WriteString("---\n\n")
	sb.WriteString("_Served live to your terminal over SSH, straight from the same " +
		"backend that powers the website._\n")
	return sb.String()
}

func linksMarkdown(p profileInfo) string {
	var sb strings.Builder
	sb.WriteString("# Links\n\n")
	sb.WriteString("| Where | What |\n|-------|------|\n")
	for _, l := range p.links {
		sb.WriteString("| " + l.label + " | " + l.url + " |\n")
	}
	sb.WriteString("\nThanks for stopping by. Press `esc` to go back.\n")
	return sb.String()
}
