import { Metadata } from "next";
import {
  ListPublishedBlogsRequest,
  ListPublishedBlogsResponse,
} from "@amirsalarsafaei/autogenerated/blogs/blogs";
import BlogsListClient from "./components/PublishedBlogs";
import { createGrpcClients } from "@/clients/grpc";

// Statically generate at build time against the live backend, then refresh in
// the background every 5 minutes (ISR) so newly published blogs show up without
// a redeploy.
export const revalidate = 300;

export const metadata: Metadata = {
  title: "Blogs | AmirSalar Safaei",
  description: "Browse my published blogs about software engineering",
};

async function getInitialBlogs() {
  // Pure/offline Nix builds (NEXT_BUILD_SKIP_BACKEND=1) have no backend to talk
  // to; return an empty page so `next build` still succeeds. The real content
  // is fetched during the on-server build that runs against the live backend.
  if (process.env.NEXT_BUILD_SKIP_BACKEND === "1") {
    return ListPublishedBlogsResponse.create({ blogs: [], nextPageToken: "" });
  }

  const { blogs_client } = createGrpcClients();

  const req = ListPublishedBlogsRequest.create({
    pageSize: 10,
    pageToken: "",
  });

  try {
    const response = await blogs_client.ListPublishedBlogs(req);
    return response;
  } catch (error) {
    console.error("Failed to fetch initial blogs:", error);
    throw error;
  }
}

export default async function PublishedBlogs() {
  const initialData = await getInitialBlogs();

  return (
    <BlogsListClient
      initialData={initialData}
      initialDataUpdatedAt={Date.now()}
    />
  );
}
