{
  lib,
  rustPlatform,
  pkg-config,
  protobuf,
  openssl,
  postgresql,
}:

rustPlatform.buildRustPackage {
  pname = "amirsalarsafaeicom-backend";
  version = "0.1.0";

  src = lib.cleanSourceWith {
    src = ../..;
    filter =
      path: type:
      let
        relPath = lib.removePrefix (toString ../.. + "/") path;
      in
      (lib.hasPrefix "backend/" relPath)
      || (lib.hasPrefix "autogenerated/rust/" relPath)
      || (lib.hasPrefix "proto/" relPath)
      || relPath == "Cargo.toml"
      || relPath == "Cargo.lock"
      || relPath == "autogenerated";
  };

  cargoLock.lockFile = ../../Cargo.lock;

  buildAndTestSubdir = "backend";

  nativeBuildInputs = [
    pkg-config
    protobuf
  ];

  buildInputs = [
    openssl
    postgresql
  ];

  env = {
    PROTOC = "${protobuf}/bin/protoc";
    OPENSSL_NO_VENDOR = "1";
  };

  doCheck = false;

  meta = {
    description = "Backend service for amirsalarsafaei.com";
    homepage = "https://amirsalarsafaei.com";
    license = lib.licenses.mit;
    mainProgram = "amirsalarsafaeicom-backend";
    platforms = lib.platforms.unix;
  };
}
