{
  lib,
  mkYarnPackage,
  nodejs_20,
  pkg-config,
  python3,
  vips,
  libiconv,
  stdenv,
  darwin,
}:

let
  nodejs = nodejs_20;

  src = lib.cleanSourceWith {
    src = ../..;
    filter =
      path: type:
      let
        relPath = lib.removePrefix (toString ../.. + "/") path;
      in
      (lib.hasPrefix "frontend" relPath)
      || (lib.hasPrefix "autogenerated/ts" relPath)
      || relPath == "autogenerated"
      || relPath == "autogenerated/package.json"
      || relPath == "autogenerated/yarn.lock";
  };
in
mkYarnPackage {
  pname = "amirsalarsafaei-frontend";
  version = "0.1.0";

  src = "${src}/frontend";

  packageJSON = ../../frontend/package.json;
  yarnLock = ../../frontend/yarn.lock;

  nativeBuildInputs = [
    pkg-config
    python3
  ];

  buildInputs = [
    vips
    libiconv
  ]
  ++ lib.optionals stdenv.isDarwin [
    darwin.apple_sdk.frameworks.CoreServices
  ];

  preBuild = ''
    mkdir -p deps/@amirsalarsafaei/frontend/../autogenerated
    cp -r ${src}/autogenerated/ts deps/@amirsalarsafaei/autogenerated/ || true
    mkdir -p deps/autogenerated
    cp -r ${src}/autogenerated/ts deps/autogenerated/ || true
  '';

  buildPhase = ''
    runHook preBuild

    export HOME=$TMPDIR
    cd deps/@amirsalarsafaei/frontend

    mkdir -p ../autogenerated
    cp -r ${src}/autogenerated/ts ../autogenerated/ || true

    yarn build

    runHook postBuild
  '';

  installPhase = ''
    runHook preInstall

    mkdir -p $out

    if [ -d ".next/standalone" ]; then
      cp -r .next/standalone/* $out/
      mkdir -p $out/.next/static
      cp -r .next/static/* $out/.next/static/
      if [ -d "public" ]; then
        cp -r public $out/
      fi
    else
      cp -r .next $out/
      cp -r node_modules $out/ || true
      cp package.json $out/
      if [ -d "public" ]; then
        cp -r public $out/
      fi
    fi

    runHook postInstall
  '';

  distPhase = "true";
  dontFixup = true;

  meta = {
    description = "Frontend for amirsalarsafaei.com";
    homepage = "https://amirsalarsafaei.com";
    license = lib.licenses.mit;
  };
}
