{
  lib,
  stdenv,
  fetchYarnDeps,
  yarnConfigHook,
  nodejs_20,
  pkg-config,
  python3,
  vips,
  libiconv,
  darwin,
  buildEnv ? "production",
}:

let
  src = lib.cleanSourceWith {
    src = ../..;
    filter =
      path: type:
      let
        relPath = lib.removePrefix (toString ../.. + "/") path;
      in
      (lib.hasPrefix "frontend" relPath)
      || (lib.hasPrefix "autogenerated/ts" relPath)
      || relPath == "autogenerated";
  };

  envVars = {
    local = {
      NEXT_PUBLIC_GRPC_WEB_URL = "http://localhost:8000";
      NEXT_PUBLIC_IMAGE_SERVER_WEB_URL = "http://localhost:3001";
    };
    production = {
      NEXT_PUBLIC_GRPC_WEB_URL = "https://grpc-api.amirsalarsafaei.com";
      NEXT_PUBLIC_IMAGE_SERVER_WEB_URL = "https://upload.amirsalarsafaei.com";
    };
  };
in
stdenv.mkDerivation {
  pname = "amirsalarsafaei-frontend";
  version = "0.1.0";

  src = "${src}/frontend";

  nativeBuildInputs = [
    nodejs_20
    yarnConfigHook
    pkg-config
    python3
  ];

  buildInputs = [
    vips
    libiconv
  ]
  ++ lib.optionals stdenv.isDarwin [
    darwin.apple_sdk.frameworks.CoreServices
  ];

  yarnOfflineCache = fetchYarnDeps {
    yarnLock = "${src}/frontend/yarn.lock";
    hash = "sha256-XKmFBrn9onKuxpW9ijqzHkxhsW8FZnJ46nlUgngUDZM=";
  };

  preBuild = ''
    # Setup autogenerated directory for proto imports
    # Copy the TypeScript files to a sibling directory
    mkdir -p ../autogenerated/ts
    cp -r ${src}/autogenerated/ts/* ../autogenerated/ts/

    # The autogenerated TS files import from packages like @bufbuild/protobuf/wire.
    # These packages are already in frontend's node_modules since they're listed
    # as dependencies in frontend/package.json. We symlink them to autogenerated
    # so the imports resolve correctly.
    mkdir -p ../autogenerated/node_modules
    ln -sf $PWD/node_modules/@bufbuild ../autogenerated/node_modules/@bufbuild
    ln -sf $PWD/node_modules/@improbable-eng ../autogenerated/node_modules/@improbable-eng
    ln -sf $PWD/node_modules/browser-headers ../autogenerated/node_modules/browser-headers
    ln -sf $PWD/node_modules/google-protobuf ../autogenerated/node_modules/google-protobuf
  '';

  buildPhase = ''
    runHook preBuild

    export HOME=$TMPDIR
    export NODE_OPTIONS="--max_old_space_size=16384"
    # Signal to the app that this is an offline/CI build - skip backend calls
    export NEXT_BUILD_SKIP_BACKEND=1
    # Next.js public env vars must be set at build time
    export NEXT_PUBLIC_GRPC_WEB_URL="${envVars.${buildEnv}.NEXT_PUBLIC_GRPC_WEB_URL}"
    export NEXT_PUBLIC_IMAGE_SERVER_WEB_URL="${envVars.${buildEnv}.NEXT_PUBLIC_IMAGE_SERVER_WEB_URL}"

    yarn build

    runHook postBuild
  '';

  installPhase = ''
    runHook preInstall

    mkdir -p $out

    # Copy the full .next directory (contains standalone/, static/, and server.js for standalone mode)
    cp -r .next $out/
    cp package.json $out/

    # For Next.js standalone mode, copy static files into .next/standalone/.next/static
    # so they're available when the server runs
    if [ -d ".next/standalone" ] && [ -d ".next/static" ]; then
      mkdir -p $out/.next/standalone/.next/static
      cp -r .next/static/* $out/.next/standalone/.next/static/
    fi

    # Copy public directory into standalone for static files
    if [ -d ".next/standalone" ] && [ -d "public" ]; then
      mkdir -p $out/.next/standalone/public
      cp -r public/* $out/.next/standalone/public/
    fi

    # Copy public directory to root as well for non-standalone mode
    [ -d "public" ] && cp -r public $out/ || true

    runHook postInstall
  '';

  meta = {
    description = "Frontend for amirsalarsafaei.com";
    homepage = "https://amirsalarsafaei.com";
    license = lib.licenses.mit;
  };
}
