# A buildable frontend source tree: the frontend sources plus the offline
# (Nix-pure) node_modules, but WITHOUT running `next build`.
#
# The actual `next build` is deferred so it can run on the server against the
# live, already-deployed backend (see the NixOS service module's
# `*-frontend-build` unit). Keeping dependency resolution here keeps it pure and
# reproducible; only the backend-data-dependent `.next` output is impure.
{
  lib,
  stdenv,
  fetchYarnDeps,
  yarnConfigHook,
  nodejs_20,
  pkg-config,
  python3,
  vips,
  libiconv,
  darwin,
}:

let
  src = lib.cleanSourceWith {
    src = ../..;
    filter =
      path: type:
      let
        relPath = lib.removePrefix (toString ../.. + "/") path;
      in
      # NB: directory entries themselves must pass the filter, otherwise the
      # whole subtree is pruned (e.g. "frontend" must match, not just
      # "frontend/...").
      relPath == "frontend"
      || (lib.hasPrefix "frontend/" relPath)
      || relPath == "autogenerated"
      || relPath == "autogenerated/ts"
      || (lib.hasPrefix "autogenerated/ts/" relPath);
  };
in
stdenv.mkDerivation {
  pname = "amirsalarsafaei-frontend-build-tree";
  version = "0.1.0";

  inherit src;
  sourceRoot = "${src.name}/frontend";

  nativeBuildInputs = [
    nodejs_20
    yarnConfigHook
    pkg-config
    python3
  ];

  buildInputs = [
    vips
    libiconv
  ]
  ++ lib.optionals stdenv.isDarwin [
    darwin.apple_sdk.frameworks.CoreServices
  ];

  yarnOfflineCache = fetchYarnDeps {
    yarnLock = "${src}/frontend/yarn.lock";
    hash = "sha256-XVMKv0s2CwKFfRaxiEYUAor6DLvtonNcGWVukpeStkc=";
  };

  # yarnConfigHook populates ./node_modules from the offline cache during the
  # configure phase. We deliberately do NOT run `next build`.
  buildPhase = ''
    runHook preBuild

    # The autogenerated TS files import from packages like @bufbuild/protobuf
    # that live in frontend/node_modules; symlink them so the imports resolve
    # both now and when `next build` later runs from the copied tree.
    #
    # These MUST be relative links. Absolute ($PWD/...) targets point into the
    # build sandbox (/build/source/frontend/node_modules), which is gone in the
    # store output — `cp -a` would copy them verbatim and the fixup phase's
    # noBrokenSymlinks check would fail on the dangling links. A relative
    # `../../frontend/node_modules/X` target resolves correctly in all three
    # layouts (build sandbox, store output, and the copied build tree), since
    # autogenerated/ and frontend/ stay siblings throughout.
    chmod -R u+w ../autogenerated
    mkdir -p ../autogenerated/node_modules
    for pkg in @bufbuild @improbable-eng browser-headers google-protobuf; do
      ln -sfn "../../frontend/node_modules/$pkg" "../autogenerated/node_modules/$pkg"
    done

    runHook postBuild
  '';

  installPhase = ''
    runHook preInstall

    mkdir -p $out
    # Preserve the frontend/ + autogenerated/ layout next.config.js expects
    # (it resolves ../autogenerated/ts relative to the frontend dir).
    cp -a . $out/frontend
    cp -a ../autogenerated $out/autogenerated

    runHook postInstall
  '';

  meta = {
    description = "Buildable frontend source tree (deps prepared, next build deferred) for amirsalarsafaei.com";
    homepage = "https://amirsalarsafaei.com";
    license = lib.licenses.mit;
    platforms = lib.platforms.unix;
  };
}
