{
  lib,
  buildGoModule,
}:

let
  src = lib.cleanSourceWith {
    src = ../..;
    filter =
      path: type:
      let
        relPath = lib.removePrefix (toString ../.. + "/") path;
      in
      # NB: directory entries themselves must pass the filter, otherwise the
      # whole subtree is pruned (e.g. "ssh" must match, not just "ssh/...").
      # The ssh module has a local `replace` onto ../autogenerated/go, so that
      # tree must be present too.
      relPath == "ssh"
      || (lib.hasPrefix "ssh/" relPath)
      || relPath == "autogenerated"
      || relPath == "autogenerated/go"
      || (lib.hasPrefix "autogenerated/go/" relPath);
  };
in
buildGoModule {
  pname = "amirsalarsafaeicom-ssh";
  version = "0.1.0";

  inherit src;

  modRoot = "ssh";

  vendorHash = "sha256-7OlvdycBY9hwiA/dEm9lTUd8FEPwbI6Yk323nNQGP30=";

  ldflags = [
    "-s"
    "-w"
  ];

  meta = {
    description = "SSH front-end for amirsalarsafaei.com (Wish + Bubble Tea)";
    homepage = "https://amirsalarsafaei.com";
    license = lib.licenses.mit;
    mainProgram = "ssh";
    platforms = lib.platforms.unix;
  };
}
