{
  lib,
  buildGoModule,
}:

let
  src = lib.cleanSourceWith {
    src = ../..;
    filter =
      path: type:
      let
        relPath = lib.removePrefix (toString ../.. + "/") path;
      in
      # NB: directory entries themselves must pass the filter, otherwise the
      # whole subtree is pruned (e.g. "tuissh" must match, not just "tuissh/...").
      # The tuissh module has a local `replace` onto ../autogenerated/go, so that
      # tree must be present too.
      relPath == "tuissh"
      || (lib.hasPrefix "tuissh/" relPath)
      || relPath == "autogenerated"
      || relPath == "autogenerated/go"
      || (lib.hasPrefix "autogenerated/go/" relPath);
  };
in
buildGoModule {
  pname = "amirsalarsafaeicom-tuissh";
  version = "0.1.0";

  inherit src;

  modRoot = "tuissh";

  vendorHash = "sha256-ifuqlh7LPZh2yDUVpyATILozSo6tWsFjp17cR1yMF+0=";

  ldflags = [
    "-s"
    "-w"
  ];

  meta = {
    description = "TUI-over-SSH front-end for amirsalarsafaei.com (Wish + Bubble Tea)";
    homepage = "https://amirsalarsafaei.com";
    license = lib.licenses.mit;
    mainProgram = "tuissh";
    platforms = lib.platforms.unix;
  };
}
