import {
  SpotifyClientImpl,
  Spotify,
  GrpcWebImpl,
} from "@amirsalarsafaei/autogenerated/playground/spotify";
import {
  BlogsClientImpl,
  Blogs,
  Tags,
  TagsClientImpl,
} from "@amirsalarsafaei/autogenerated/blogs/blogs";
import {
  ProfileClientImpl,
  Profile,
} from "@amirsalarsafaei/autogenerated/profile/profile";
import { NodeHttpTransport } from "@improbable-eng/grpc-web-node-http-transport";
import { grpc } from "@improbable-eng/grpc-web";

// Dynamically import NodeHttpTransport only on server-side
const getNodeHttpTransport = () => {
  if (typeof window === "undefined") {
    try {
      // eslint-disable-next-line @typescript-eslint/no-var-requires
      const {
        NodeHttpTransport,
      } = require("@improbable-eng/grpc-web-node-http-transport");
      return NodeHttpTransport;
    } catch (error) {
      console.warn("NodeHttpTransport not available:", error);
      return null;
    }
  }
  return null;
};

// Resolve the gRPC-web endpoint. On the server (SSR, build-time SSG/ISR, and
// generateStaticParams/generateMetadata) prefer GRPC_WEB_INTERNAL_URL so we can
// hit the backend directly over localhost without going through the public
// nginx/TLS path. In the browser, only the NEXT_PUBLIC_* value is available
// (and it's the only one that gets inlined into the client bundle), so server
// and browser deliberately use different URLs.
function getGrpcWebUrl(): string {
  if (typeof window === "undefined") {
    return (
      process.env.GRPC_WEB_INTERNAL_URL ||
      process.env.NEXT_PUBLIC_GRPC_WEB_URL ||
      "http://localhost:8000"
    );
  }

  return process.env.NEXT_PUBLIC_GRPC_WEB_URL || "http://localhost:8000";
}

interface GrpcClients {
  spotify_client: Spotify;
  blogs_client: Blogs;
  tags_client: Tags;
  profile_client: Profile;
}

let clientInstance: GrpcClients | null = null;

export function createGrpcClients(): GrpcClients {
  if (clientInstance) {
    return clientInstance;
  }

  const NodeHttpTransport = getNodeHttpTransport();

  if (!isClient() && NodeHttpTransport) {
    grpc.setDefaultTransport(NodeHttpTransport());
  }

  const transport = new GrpcWebImpl(getGrpcWebUrl(), {
    debug: process.env.NODE_ENV === "development",
    transport:
      typeof window === "undefined" && NodeHttpTransport
        ? NodeHttpTransport()
        : undefined,
  });

  clientInstance = {
    tags_client: new TagsClientImpl(transport),
    spotify_client: new SpotifyClientImpl(transport),
    blogs_client: new BlogsClientImpl(transport),
    profile_client: new ProfileClientImpl(transport),
  };

  return clientInstance;
}

export function isClient(): boolean {
  return typeof window !== "undefined";
}
// Default transport is set dynamically in createGrpcClients()
