import nextDynamic from "next/dynamic";
import styles from "./page.module.scss";
import { InlineCode } from "@/components/InlineCode/InlineCode";
import { CodeBlock } from "@/components/CodeBlock/CodeBlock";
import { createGrpcClients } from "@/clients/grpc";
import {
  GetProfileRequest,
  Skill_Level,
} from "@amirsalarsafaei/autogenerated/profile/profile";

// Proficiency bars are rendered from the Skill.Level enum: a filled-block count
// out of BAR_WIDTH plus the lowercase label. "passion" denotes enthusiasm
// rather than mastery, so it sits between learning and proficient.
const BAR_WIDTH = 5;
const LEVEL_SCORE: Record<string, number> = {
  [Skill_Level.EXPERT]: 5,
  [Skill_Level.PROFICIENT]: 4,
  [Skill_Level.PASSION]: 3,
  [Skill_Level.LEARNING]: 2,
  [Skill_Level.LEVEL_UNSPECIFIED]: 0,
};
const LEVEL_LABEL: Record<string, string> = {
  [Skill_Level.EXPERT]: "expert",
  [Skill_Level.PROFICIENT]: "proficient",
  [Skill_Level.PASSION]: "passion",
  [Skill_Level.LEARNING]: "learning",
  [Skill_Level.LEVEL_UNSPECIFIED]: "",
};

// Statically generated against the backend (the same Profile RPC the SSH
// terminal at ssh.amirsalarsafaei.com consumes, so there's a single source of
// truth) and revalidated hourly via ISR.
export const revalidate = 3600;

const ThreeDCanvas = nextDynamic(
  () => import("./components/AboutMe3DCanvas"),
  {
    ssr: false,
  },
);

// Fallback used if the backend is unreachable (and at offline `next build`
// time, since the production Nix build sets NEXT_BUILD_SKIP_BACKEND=1 and ISR
// refreshes against the backend hourly), so the page still renders fully.
const FALLBACK_PROFILE = {
  name: "AmirSalar Safaei",
  title: "Software Engineer & System Architect",
  bio: `Hello! I'm a passionate software engineer currently pursuing my
M.Sc. in Computer Science at the University of British Columbia.

I love building distributed systems and writing type-safe & maintainable code.`,
  currentFocus: `# Current Focus 🎯

## At Work (Divar)
- Building scalable backend services
- Improving system performance and reliability

## Personal Projects
- Contributing to open source projects
- Building developer tools and libraries

## Learning
- Advanced system design patterns
- Kubernetes and cloud-native technologies`,
  skills: [
    { name: "golang", level: Skill_Level.EXPERT },
    { name: "python", level: Skill_Level.EXPERT },
    { name: "typescript", level: Skill_Level.EXPERT },
    { name: "rust", level: Skill_Level.PROFICIENT },
    { name: "java", level: Skill_Level.PROFICIENT },
    { name: "cpp", level: Skill_Level.LEARNING },
    { name: "distributed-systems", level: Skill_Level.PASSION },
    { name: "concurrent-programming", level: Skill_Level.PASSION },
    { name: "type-safety", level: Skill_Level.PASSION },
    { name: "open-source", level: Skill_Level.PASSION },
  ],
  resume: {
    fullName: "AmirSalar Safaei Ghaderi",
    email: "amirsalarsafaeighaderi@gmail.com",
    githubUrl: "https://github.com/amirsalarsafaei",
    sections: [
      {
        heading: "Education",
        body: `Sharif University of Technology Tehran, Iran
Bachelors of science in Computer science
GPA: 17.9/20
2020 - 2025`,
      },
    ],
  },
  links: [
    { label: "Website", url: "https://amirsalarsafaei.com" },
    { label: "GitHub", url: "https://github.com/amirsalarsafaei" },
    { label: "Email", url: "mailto:amirs.s.g.o@gmail.com" },
    { label: "Telegram", url: "https://t.me/amirsalarsafaei" },
    { label: "LinkedIn", url: "https://linkedin.com/in/amir-salar-safaei" },
  ],
};

async function getProfile() {
  // Pure/offline Nix builds have no backend; skip the call and use the fallback
  // so `next build` doesn't hang on a connection that can never succeed.
  if (process.env.NEXT_BUILD_SKIP_BACKEND === "1") {
    return FALLBACK_PROFILE;
  }

  try {
    const { profile_client } = createGrpcClients();
    return await profile_client.GetProfile(GetProfileRequest.create({}));
  } catch (error) {
    console.error("Failed to fetch profile:", error);
    return FALLBACK_PROFILE;
  }
}

export default async function AboutMe() {
  const profile = await getProfile();

  return (
    <div className={styles.aboutContainer}>
      <div className={styles.terminal}>
        <div className={styles.terminalHeader}>
          <div className={styles.buttons}>
            <span className={styles.close}></span>
            <span className={styles.minimize}></span>
            <span className={styles.maximize}></span>
          </div>
          <div className={styles.termTitle}>about_me.sh</div>
        </div>

        <div className={styles.terminalBody}>
          <div className={styles.line}>
            <span className={styles.prompt}>visitor@amirsalar:~$</span> whoami
          </div>
          <div className={styles.content}>
            <pre>
              {`${profile.name}
${profile.title}`}
            </pre>
          </div>

          <div className={styles.line}>
            <span className={styles.prompt}>visitor@amirsalar:~$</span> cat
            story.md
          </div>
          <div className={styles.content}>
            <pre>{profile.bio}</pre>
          </div>

          <div className={styles.line}>
            <span className={styles.prompt}>visitor@amirsalar:~$</span> skills
          </div>
          <div className={styles.content}>
            <pre>
              {profile.skills?.map((s) => {
                const score = LEVEL_SCORE[s.level] ?? 0;
                return (
                  <span key={s.name}>
                    {s.name.padEnd(24)}
                    <span className={styles.barFilled}>
                      {"█".repeat(score)}
                    </span>
                    <span className={styles.barEmpty}>
                      {"░".repeat(BAR_WIDTH - score)}
                    </span>
                    {`  ${LEVEL_LABEL[s.level] ?? ""}\n`}
                  </span>
                );
              })}
            </pre>
          </div>

          <div className={styles.line}>
            <span className={styles.prompt}>visitor@amirsalar:~$</span> cat
            current_focus.md
          </div>
          <div className={styles.content}>
            <pre>{profile.currentFocus}</pre>
          </div>

          <div className={styles.line}>
            <span className={styles.prompt}>visitor@amirsalar:~$</span> cat
            cv.md
          </div>
          <div className={styles.resumeContent}>
            <h1>{profile.resume?.fullName}</h1>
            <p className={styles.contact}>
              <InlineCode>{profile.resume?.email}</InlineCode> §{" "}
              <a
                href={profile.resume?.githubUrl}
                target="_blank"
                rel="noopener noreferrer"
              >
                {profile.resume?.githubUrl?.replace(/^https?:\/\//, "")}
              </a>
            </p>

            {profile.resume?.sections?.map((section) => (
              <section key={section.heading}>
                <h2>$ {section.heading}</h2>
                <CodeBlock language="markdown">{section.body}</CodeBlock>
              </section>
            ))}
          </div>

          <div className={styles.line}>
            <span className={styles.prompt}>visitor@amirsalar:~$</span> cat
            links.md
          </div>
          <div className={styles.content}>
            <pre>
              {"Let's connect!\n\n"}
              {profile.links?.map((link) => {
                const isWeb = link.url.startsWith("http");
                const isMail = link.url.startsWith("mailto:");
                return (
                  <span key={link.label}>
                    {`${link.label.padEnd(9)} `}
                    {isWeb || isMail ? (
                      <a
                        href={link.url}
                        target={isWeb ? "_blank" : undefined}
                        rel={isWeb ? "noopener noreferrer" : undefined}
                      >
                        {link.url.replace(/^mailto:/, "")}
                      </a>
                    ) : (
                      <InlineCode>{link.url}</InlineCode>
                    )}
                    {"\n"}
                  </span>
                );
              })}
              {"\nAlways open to interesting conversations and collaborations!"}
            </pre>
          </div>

          <div className={styles.line}>
            <span className={styles.prompt}>visitor@amirsalar:~$</span>{" "}
            <span className={styles.cursor}>█</span>
          </div>
        </div>
      </div>

      <ThreeDCanvas />
    </div>
  );
}
