/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/go_gopher.glb --T -k -t -o src/modules/playground/models/Gopher.tsx 
Files: public/go_gopher.glb [743.09KB] > /home/amirsalar/personal/amirsalarsafaei.com/src/modules/playground/models/go_gopher-transformed.glb [62.46KB] (92%)
Author: Mysticreator (https://sketchfab.com/Mysticreator)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/go-gopher-e0e18cb276574666a39d2a0926510fc1
Title: Go Gopher
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Object_4: THREE.Mesh
    Object_6: THREE.Mesh
    Object_12: THREE.Mesh
    Object_14: THREE.Mesh
  }
  materials: {
    Material: THREE.MeshStandardMaterial
    ['Material.001']: THREE.MeshStandardMaterial
    ['Material.002']: THREE.MeshStandardMaterial
    ['Material.003']: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

export default function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/go_gopher-transformed.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh name="Object_4" geometry={nodes.Object_4.geometry} material={materials.Material} />
      <mesh name="Object_6" geometry={nodes.Object_6.geometry} material={materials['Material.001']} position={[0.215, 0.276, 0.959]} scale={0.321} />
      <mesh name="Object_12" geometry={nodes.Object_12.geometry} material={materials['Material.002']} position={[0.27, 0.558, 1.192]} rotation={[-0.013, -0.006, -0.07]} scale={0.14} />
      <mesh name="Object_14" geometry={nodes.Object_14.geometry} material={materials['Material.003']} position={[0.213, 0.124, 1.032]} rotation={[-0.001, 0, -0.049]} scale={0.102} />
    </group>
  )
}

useGLTF.preload('/go_gopher-transformed.glb')
