/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.4.1 public/laptop-2.glb --output ./src/modules/playground/models/LaptopModel.tsx --types -k 
*/

import * as THREE from 'three'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    body_laptop_body_laptop_0: THREE.Mesh
    conncector_komponen_0: THREE.Mesh
    cover_bawah_komponen_0: THREE.Mesh
    hardware_hardware_0: THREE.Mesh
    keyboard_keyboard_0: THREE.Mesh
    keyboard_keyboard_0001: THREE.Mesh
    keyboard_keyboard_0002: THREE.Mesh
    keyboard_keyboard_0003: THREE.Mesh
    keyboard_keyboard_0004: THREE.Mesh
    keyboard_keyboard_0005: THREE.Mesh
    keyboard_keyboard_0006: THREE.Mesh
    keyboard_keyboard_0007: THREE.Mesh
    keyboard_keyboard_0008: THREE.Mesh
    keyboard_keyboard_0009: THREE.Mesh
    keyboard_keyboard_0010: THREE.Mesh
    keyboard_keyboard_0011: THREE.Mesh
    keyboard_keyboard_0012: THREE.Mesh
    keyboard_keyboard_0013: THREE.Mesh
    keyboard_keyboard_0014: THREE.Mesh
    keyboard_keyboard_0015: THREE.Mesh
    keyboard_keyboard_0016: THREE.Mesh
    keyboard_keyboard_0017: THREE.Mesh
    keyboard_keyboard_0018: THREE.Mesh
    keyboard_keyboard_0019: THREE.Mesh
    keyboard_keyboard_0020: THREE.Mesh
    keyboard_keyboard_0021: THREE.Mesh
    keyboard_keyboard_0022: THREE.Mesh
    keyboard_keyboard_0023: THREE.Mesh
    keyboard_keyboard_0024: THREE.Mesh
    keyboard_keyboard_0025: THREE.Mesh
    keyboard_keyboard_0026: THREE.Mesh
    keyboard_keyboard_0027: THREE.Mesh
    keyboard_keyboard_0028: THREE.Mesh
    keyboard_keyboard_0029: THREE.Mesh
    keyboard_keyboard_0030: THREE.Mesh
    keyboard_keyboard_0031: THREE.Mesh
    keyboard_keyboard_0032: THREE.Mesh
    keyboard_keyboard_0033: THREE.Mesh
    keyboard_keyboard_0034: THREE.Mesh
    keyboard_keyboard_0035: THREE.Mesh
    keyboard_keyboard_0036: THREE.Mesh
    keyboard_keyboard_0037: THREE.Mesh
    keyboard_keyboard_0038: THREE.Mesh
    keyboard_keyboard_0039: THREE.Mesh
    keyboard_keyboard_0040: THREE.Mesh
    keyboard_keyboard_0041: THREE.Mesh
    keyboard_keyboard_0042: THREE.Mesh
    keyboard_keyboard_0043: THREE.Mesh
    keyboard_keyboard_0044: THREE.Mesh
    keyboard_keyboard_0045: THREE.Mesh
    keyboard_keyboard_0046: THREE.Mesh
    keyboard_keyboard_0047: THREE.Mesh
    keyboard_keyboard_0048: THREE.Mesh
    keyboard_keyboard_0049: THREE.Mesh
    keyboard_keyboard_0050: THREE.Mesh
    keyboard_keyboard_0051: THREE.Mesh
    keyboard_keyboard_0052: THREE.Mesh
    keyboard_keyboard_0053: THREE.Mesh
    keyboard_keyboard_0054: THREE.Mesh
    keyboard_keyboard_0055: THREE.Mesh
    keyboard_keyboard_0056: THREE.Mesh
    keyboard_keyboard_0057: THREE.Mesh
    keyboard_keyboard_0058: THREE.Mesh
    keyboard_keyboard_0059: THREE.Mesh
    keyboard_keyboard_0060: THREE.Mesh
    keyboard_keyboard_0061: THREE.Mesh
    keyboard_keyboard_0062: THREE.Mesh
    keyboard_keyboard_0063: THREE.Mesh
    keyboard_keyboard_0064: THREE.Mesh
    keyboard_keyboard_0065: THREE.Mesh
    keyboard_keyboard_0066: THREE.Mesh
    keyboard_keyboard_0067: THREE.Mesh
    keyboard_keyboard_0068: THREE.Mesh
    keyboard_keyboard_0069: THREE.Mesh
    keyboard_keyboard_0070: THREE.Mesh
    keyboard_keyboard_0071: THREE.Mesh
    keyboard_keyboard_0072: THREE.Mesh
    keyboard_keyboard_0073: THREE.Mesh
    keyboard_keyboard_0074: THREE.Mesh
    keyboard_keyboard_0075: THREE.Mesh
    keyboard_keyboard_0076: THREE.Mesh
    keyboard_keyboard_0077: THREE.Mesh
    keyboard_keyboard_0078: THREE.Mesh
    keyboard_keyboard_0079: THREE.Mesh
    keyboard_keyboard_0080: THREE.Mesh
    keyboard_keyboard_0081: THREE.Mesh
    keyboard_keyboard_0082: THREE.Mesh
    keyboard_keyboard_0083: THREE.Mesh
    keyboard_keyboard_0084: THREE.Mesh
    keyboard_keyboard_0085: THREE.Mesh
    keyboard_keyboard_0086: THREE.Mesh
    keyboard_keyboard_0087: THREE.Mesh
    keyboard_keyboard_0088: THREE.Mesh
    keyboard_keyboard_0089: THREE.Mesh
    keyboard_keyboard_0090: THREE.Mesh
    keyboard_keyboard_0091: THREE.Mesh
    keyboard_keyboard_0092: THREE.Mesh
    keyboard_keyboard_0093: THREE.Mesh
    keyboard_keyboard_0094: THREE.Mesh
    keyboard_keyboard_0095: THREE.Mesh
    keyboard_keyboard_0096: THREE.Mesh
    keyboard_keyboard_0097: THREE.Mesh
    keyboard_keyboard_0098: THREE.Mesh
    keyboard_keyboard_0099: THREE.Mesh
    keyboard_keyboard_0100: THREE.Mesh
    keyboard_keyboard_0101: THREE.Mesh
    keyboard_keyboard_0102: THREE.Mesh
    keyboard_keyboard_0103: THREE.Mesh
    keyboard_keyboard_0104: THREE.Mesh
    keyboard_keyboard_0105: THREE.Mesh
    keyboard_keyboard_0106: THREE.Mesh
    keyboard_keyboard_0107: THREE.Mesh
    keyboard_keyboard_0108: THREE.Mesh
    keyboard_keyboard_0109: THREE.Mesh
    keyboard_keyboard_0110: THREE.Mesh
    keyboard_keyboard_0111: THREE.Mesh
    keyboard_keyboard_0112: THREE.Mesh
    keyboard_keyboard_0113: THREE.Mesh
    keyboard_keyboard_0114: THREE.Mesh
    keyboard_keyboard_0115: THREE.Mesh
    keyboard_keyboard_0116: THREE.Mesh
    keyboard_keyboard_0117: THREE.Mesh
    keyboard_keyboard_0118: THREE.Mesh
    keyboard_keyboard_0119: THREE.Mesh
    keyboard_keyboard_0120: THREE.Mesh
    keyboard_keyboard_0121: THREE.Mesh
    keyboard_keyboard_0122: THREE.Mesh
    keyboard_keyboard_0123: THREE.Mesh
    keyboard_keyboard_0124: THREE.Mesh
    keyboard_keyboard_0125: THREE.Mesh
    keyboard_keyboard_0126: THREE.Mesh
    keyboard_keyboard_0127: THREE.Mesh
    keyboard_keyboard_0128: THREE.Mesh
    keyboard_keyboard_0129: THREE.Mesh
    keyboard_keyboard_0130: THREE.Mesh
    keyboard_keyboard_0131: THREE.Mesh
    keyboard_keyboard_0132: THREE.Mesh
    keyboard_keyboard_0133: THREE.Mesh
    keyboard_keyboard_0134: THREE.Mesh
    keyboard_keyboard_0135: THREE.Mesh
    keyboard_keyboard_0136: THREE.Mesh
    keyboard_keyboard_0137: THREE.Mesh
    keyboard_keyboard_0138: THREE.Mesh
    keyboard_keyboard_0139: THREE.Mesh
    keyboard_keyboard_0140: THREE.Mesh
    keyboard_keyboard_0141: THREE.Mesh
    keyboard_keyboard_0142: THREE.Mesh
    keyboard_keyboard_0143: THREE.Mesh
    keyboard_keyboard_0144: THREE.Mesh
    keyboard_keyboard_0145: THREE.Mesh
    keyboard_keyboard_0146: THREE.Mesh
    keyboard_keyboard_0147: THREE.Mesh
    keyboard_keyboard_0148: THREE.Mesh
    keyboard_keyboard_0149: THREE.Mesh
    keyboard_keyboard_0150: THREE.Mesh
    keyboard_keyboard_0151: THREE.Mesh
    keyboard_keyboard_0152: THREE.Mesh
    keyboard_keyboard_0153: THREE.Mesh
    keyboard_keyboard_0154: THREE.Mesh
    keyboard_keyboard_0155: THREE.Mesh
    keyboard_keyboard_0156: THREE.Mesh
    keyboard_keyboard_0157: THREE.Mesh
    keyboard_keyboard_0158: THREE.Mesh
    keyboard_keyboard_0159: THREE.Mesh
    keyboard_keyboard_0160: THREE.Mesh
    keyboard_keyboard_0161: THREE.Mesh
    keyboard_keyboard_0162: THREE.Mesh
    keyboard_keyboard_0163: THREE.Mesh
    keyboard_keyboard_0164: THREE.Mesh
    keyboard_keyboard_0165: THREE.Mesh
    keyboard_keyboard_0166: THREE.Mesh
    keyboard_keyboard_0167: THREE.Mesh
    keyboard_keyboard_0168: THREE.Mesh
    keyboard_keyboard_0169: THREE.Mesh
    keyboard_keyboard_0170: THREE.Mesh
    keyboard_keyboard_0171: THREE.Mesh
    keyboard_keyboard_0172: THREE.Mesh
    keyboard_keyboard_0173: THREE.Mesh
    keyboard_keyboard_0174: THREE.Mesh
    keyboard_keyboard_0175: THREE.Mesh
    keyboard_keyboard_0176: THREE.Mesh
    keyboard_keyboard_0177: THREE.Mesh
    keyboard_keyboard_0178: THREE.Mesh
    keyboard_keyboard_0179: THREE.Mesh
    keyboard_keyboard_0180: THREE.Mesh
    keyboard_keyboard_0181: THREE.Mesh
    keyboard_keyboard_0182: THREE.Mesh
    keyboard_keyboard_0183: THREE.Mesh
    keyboard_keyboard_0184: THREE.Mesh
    keyboard_keyboard_0185: THREE.Mesh
    keyboard_keyboard_0186: THREE.Mesh
    keyboard_keyboard_0187: THREE.Mesh
    keyboard_keyboard_0188: THREE.Mesh
    keyboard_keyboard_0189: THREE.Mesh
    keyboard_keyboard_0190: THREE.Mesh
    keyboard_keyboard_0191: THREE.Mesh
    keyboard_keyboard_0192: THREE.Mesh
    keyboard_keyboard_0193: THREE.Mesh
    keyboard_keyboard_0194: THREE.Mesh
    keyboard_keyboard_0195: THREE.Mesh
    keyboard_keyboard_0196: THREE.Mesh
    keyboard_keyboard_0197: THREE.Mesh
    keyboard_keyboard_0198: THREE.Mesh
    keyboard_keyboard_0199: THREE.Mesh
    keyboard_keyboard_0200: THREE.Mesh
    keyboard_keyboard_0201: THREE.Mesh
    keyboard_keyboard_0202: THREE.Mesh
    keyboard_keyboard_0203: THREE.Mesh
    keyboard_keyboard_0204: THREE.Mesh
    keyboard_keyboard_0205: THREE.Mesh
    keyboard_keyboard_0206: THREE.Mesh
    keyboard_keyboard_0207: THREE.Mesh
    keyboard_keyboard_0208: THREE.Mesh
    keyboard_keyboard_0209: THREE.Mesh
    keyboard_keyboard_0210: THREE.Mesh
    keyboard_keyboard_0211: THREE.Mesh
    keyboard_keyboard_0212: THREE.Mesh
    keyboard_keyboard_0213: THREE.Mesh
    keyboard_keyboard_0214: THREE.Mesh
    keyboard_keyboard_0215: THREE.Mesh
    keyboard_keyboard_0216: THREE.Mesh
    keyboard_keyboard_0217: THREE.Mesh
    keyboard_keyboard_0218: THREE.Mesh
    keyboard_keyboard_0219: THREE.Mesh
    keyboard_keyboard_0220: THREE.Mesh
    keyboard_keyboard_0221: THREE.Mesh
    keyboard_keyboard_0222: THREE.Mesh
    keyboard_keyboard_0223: THREE.Mesh
    keyboard_keyboard_0224: THREE.Mesh
    keyboard_keyboard_0225: THREE.Mesh
    keyboard_keyboard_0226: THREE.Mesh
    keyboard_keyboard_0227: THREE.Mesh
    keyboard_keyboard_0228: THREE.Mesh
    keyboard_keyboard_0229: THREE.Mesh
    keyboard_keyboard_0230: THREE.Mesh
    keyboard_keyboard_0231: THREE.Mesh
    keyboard_keyboard_0232: THREE.Mesh
    keyboard_keyboard_0233: THREE.Mesh
    keyboard_keyboard_0234: THREE.Mesh
    keyboard_keyboard_0235: THREE.Mesh
    keyboard_keyboard_0236: THREE.Mesh
    keyboard_keyboard_0237: THREE.Mesh
    keyboard_keyboard_0238: THREE.Mesh
    keyboard_keyboard_0239: THREE.Mesh
    keyboard_keyboard_0240: THREE.Mesh
    keyboard_keyboard_0241: THREE.Mesh
    keyboard_keyboard_0242: THREE.Mesh
    keyboard_keyboard_0243: THREE.Mesh
    keyboard_keyboard_0244: THREE.Mesh
    keyboard_keyboard_0245: THREE.Mesh
    keyboard_keyboard_0246: THREE.Mesh
    keyboard_keyboard_0247: THREE.Mesh
    keyboard_keyboard_0248: THREE.Mesh
    keyboard_keyboard_0249: THREE.Mesh
    keyboard_keyboard_0250: THREE.Mesh
    keyboard_keyboard_0251: THREE.Mesh
    keyboard_keyboard_0252: THREE.Mesh
    keyboard_keyboard_0253: THREE.Mesh
    keyboard_keyboard_0254: THREE.Mesh
    keyboard_keyboard_0255: THREE.Mesh
    keyboard_keyboard_0256: THREE.Mesh
    keyboard_keyboard_0257: THREE.Mesh
    keyboard_keyboard_0258: THREE.Mesh
    keyboard_keyboard_0259: THREE.Mesh
    keyboard_keyboard_0260: THREE.Mesh
    keyboard_keyboard_0261: THREE.Mesh
    keyboard_keyboard_0262: THREE.Mesh
    keyboard_keyboard_0263: THREE.Mesh
    keyboard_keyboard_0264: THREE.Mesh
    keyboard_keyboard_0265: THREE.Mesh
    keyboard_keyboard_0266: THREE.Mesh
    keyboard_keyboard_0267: THREE.Mesh
    keyboard_keyboard_0268: THREE.Mesh
    keyboard_keyboard_0269: THREE.Mesh
    keyboard_keyboard_0270: THREE.Mesh
    keyboard_keyboard_0271: THREE.Mesh
    keyboard_keyboard_0272: THREE.Mesh
    keyboard_keyboard_0273: THREE.Mesh
    keyboard_keyboard_0274: THREE.Mesh
    keyboard_keyboard_0275: THREE.Mesh
    keyboard_keyboard_0276: THREE.Mesh
    keyboard_keyboard_0277: THREE.Mesh
    keyboard_keyboard_0278: THREE.Mesh
    keyboard_keyboard_0279: THREE.Mesh
    keyboard_keyboard_0280: THREE.Mesh
    keyboard_keyboard_0281: THREE.Mesh
    keyboard_keyboard_0282: THREE.Mesh
    keyboard_keyboard_0283: THREE.Mesh
    keyboard_keyboard_0284: THREE.Mesh
    keyboard_keyboard_0285: THREE.Mesh
    keyboard_keyboard_0286: THREE.Mesh
    keyboard_keyboard_0287: THREE.Mesh
    keyboard_keyboard_0288: THREE.Mesh
    keyboard_keyboard_0289: THREE.Mesh
    keyboard_keyboard_0290: THREE.Mesh
    keyboard_keyboard_0291: THREE.Mesh
    keyboard_keyboard_0292: THREE.Mesh
    keyboard_keyboard_0293: THREE.Mesh
    keyboard_keyboard_0294: THREE.Mesh
    keyboard_keyboard_0295: THREE.Mesh
    keyboard_keyboard_0296: THREE.Mesh
    keyboard_keyboard_0297: THREE.Mesh
    keyboard_keyboard_0298: THREE.Mesh
    keyboard_keyboard_0299: THREE.Mesh
    keyboard_keyboard_0300: THREE.Mesh
    keyboard_keyboard_0301: THREE.Mesh
    keyboard_keyboard_0302: THREE.Mesh
    keyboard_keyboard_0303: THREE.Mesh
    keyboard_keyboard_0304: THREE.Mesh
    keyboard_keyboard_0305: THREE.Mesh
    keyboard_keyboard_0306: THREE.Mesh
    keyboard_keyboard_0307: THREE.Mesh
    keyboard_keyboard_0308: THREE.Mesh
    keyboard_keyboard_0309: THREE.Mesh
    keyboard_keyboard_0310: THREE.Mesh
    keyboard_keyboard_0311: THREE.Mesh
    keyboard_keyboard_0312: THREE.Mesh
    keyboard_keyboard_0313: THREE.Mesh
    keyboard_keyboard_0314: THREE.Mesh
    keyboard_keyboard_0315: THREE.Mesh
    keyboard_keyboard_0316: THREE.Mesh
    keyboard_keyboard_0317: THREE.Mesh
    keyboard_keyboard_0318: THREE.Mesh
    keyboard_keyboard_0319: THREE.Mesh
    keyboard_keyboard_0320: THREE.Mesh
    keyboard_keyboard_0321: THREE.Mesh
    keyboard_keyboard_0322: THREE.Mesh
    keyboard_keyboard_0323: THREE.Mesh
    keyboard_keyboard_0324: THREE.Mesh
    keyboard_keyboard_0325: THREE.Mesh
    keyboard_keyboard_0326: THREE.Mesh
    keyboard_keyboard_0327: THREE.Mesh
    keyboard_keyboard_0328: THREE.Mesh
    keyboard_keyboard_0329: THREE.Mesh
    keyboard_keyboard_0330: THREE.Mesh
    keyboard_keyboard_0331: THREE.Mesh
    keyboard_keyboard_0332: THREE.Mesh
    keyboard_keyboard_0333: THREE.Mesh
    keyboard_keyboard_0334: THREE.Mesh
    keyboard_keyboard_0335: THREE.Mesh
    keyboard_keyboard_0336: THREE.Mesh
    keyboard_keyboard_0337: THREE.Mesh
    keyboard_keyboard_0338: THREE.Mesh
    keyboard_keyboard_0339: THREE.Mesh
    keyboard_keyboard_0340: THREE.Mesh
    keyboard_keyboard_0341: THREE.Mesh
    keyboard_keyboard_0342: THREE.Mesh
    keyboard_keyboard_0343: THREE.Mesh
    keyboard_keyboard_0344: THREE.Mesh
    keyboard_keyboard_0345: THREE.Mesh
    keyboard_keyboard_0346: THREE.Mesh
    keyboard_keyboard_0347: THREE.Mesh
    keyboard_keyboard_0348: THREE.Mesh
    keyboard_keyboard_0349: THREE.Mesh
    keyboard_keyboard_0350: THREE.Mesh
    keyboard_keyboard_0351: THREE.Mesh
    keyboard_keyboard_0352: THREE.Mesh
    keyboard_keyboard_0353: THREE.Mesh
    keyboard_keyboard_0354: THREE.Mesh
    keyboard_keyboard_0355: THREE.Mesh
    keyboard_keyboard_0356: THREE.Mesh
    keyboard_keyboard_0357: THREE.Mesh
    keyboard_keyboard_0358: THREE.Mesh
    keyboard_keyboard_0359: THREE.Mesh
    keyboard_keyboard_0360: THREE.Mesh
    keyboard_keyboard_0361: THREE.Mesh
    keyboard_keyboard_0362: THREE.Mesh
    keyboard_keyboard_0363: THREE.Mesh
    keyboard_keyboard_0364: THREE.Mesh
    keyboard_keyboard_0365: THREE.Mesh
    keyboard_keyboard_0366: THREE.Mesh
    keyboard_keyboard_0367: THREE.Mesh
    keyboard_keyboard_0368: THREE.Mesh
    keyboard_keyboard_0369: THREE.Mesh
    keyboard_keyboard_0370: THREE.Mesh
    keyboard_keyboard_0371: THREE.Mesh
    keyboard_keyboard_0372: THREE.Mesh
    keyboard_keyboard_0373: THREE.Mesh
    keyboard_keyboard_0374: THREE.Mesh
    keyboard_keyboard_0375: THREE.Mesh
    keyboard_keyboard_0376: THREE.Mesh
    keyboard_keyboard_0377: THREE.Mesh
    keyboard_keyboard_0378: THREE.Mesh
    keyboard_keyboard_0379: THREE.Mesh
    keyboard_keyboard_0380: THREE.Mesh
    keyboard_keyboard_0381: THREE.Mesh
    keyboard_keyboard_0382: THREE.Mesh
    keyboard_keyboard_0383: THREE.Mesh
    keyboard_keyboard_0384: THREE.Mesh
    keyboard_keyboard_0385: THREE.Mesh
    keyboard_keyboard_0386: THREE.Mesh
    keyboard_keyboard_0387: THREE.Mesh
    keyboard_keyboard_0388: THREE.Mesh
    keyboard_keyboard_0389: THREE.Mesh
    keyboard_keyboard_0390: THREE.Mesh
    keyboard_keyboard_0391: THREE.Mesh
    keyboard_keyboard_0392: THREE.Mesh
    keyboard_keyboard_0393: THREE.Mesh
    keyboard_keyboard_0394: THREE.Mesh
    keyboard_keyboard_0395: THREE.Mesh
    keyboard_keyboard_0396: THREE.Mesh
    keyboard_keyboard_0397: THREE.Mesh
    keyboard_keyboard_0398: THREE.Mesh
    keyboard_keyboard_0399: THREE.Mesh
    keyboard_keyboard_0400: THREE.Mesh
    keyboard_keyboard_0401: THREE.Mesh
    keyboard_keyboard_0402: THREE.Mesh
    keyboard_keyboard_0403: THREE.Mesh
    keyboard_keyboard_0404: THREE.Mesh
    keyboard_keyboard_0405: THREE.Mesh
    keyboard_keyboard_0406: THREE.Mesh
    keyboard_keyboard_0407: THREE.Mesh
    keyboard_keyboard_0408: THREE.Mesh
    keyboard_keyboard_0409: THREE.Mesh
    keyboard_keyboard_0410: THREE.Mesh
    keyboard_keyboard_0411: THREE.Mesh
    keyboard_keyboard_0412: THREE.Mesh
    keyboard_keyboard_0413: THREE.Mesh
    keyboard_keyboard_0414: THREE.Mesh
    keyboard_keyboard_0415: THREE.Mesh
    keyboard_keyboard_0416: THREE.Mesh
    keyboard_keyboard_0417: THREE.Mesh
    keyboard_keyboard_0418: THREE.Mesh
    keyboard_keyboard_0419: THREE.Mesh
    keyboard_keyboard_0420: THREE.Mesh
    keyboard_keyboard_0421: THREE.Mesh
    keyboard_keyboard_0422: THREE.Mesh
    keyboard_keyboard_0423: THREE.Mesh
    keyboard_keyboard_0424: THREE.Mesh
    keyboard_keyboard_0425: THREE.Mesh
    keyboard_keyboard_0426: THREE.Mesh
    keyboard_keyboard_0427: THREE.Mesh
    keyboard_keyboard_0428: THREE.Mesh
    keyboard_keyboard_0429: THREE.Mesh
    keyboard_keyboard_0430: THREE.Mesh
    keyboard_keyboard_0431: THREE.Mesh
    keyboard_keyboard_0432: THREE.Mesh
    keyboard_keyboard_0433: THREE.Mesh
    keyboard_keyboard_0434: THREE.Mesh
    keyboard_keyboard_0435: THREE.Mesh
    keyboard_keyboard_0436: THREE.Mesh
    keyboard_keyboard_0437: THREE.Mesh
    keyboard_keyboard_0438: THREE.Mesh
    keyboard_keyboard_0439: THREE.Mesh
    keyboard_keyboard_0440: THREE.Mesh
    keyboard_keyboard_0441: THREE.Mesh
    keyboard_keyboard_0442: THREE.Mesh
    keyboard_keyboard_0443: THREE.Mesh
    keyboard_keyboard_0444: THREE.Mesh
    keyboard_keyboard_0445: THREE.Mesh
    keyboard_keyboard_0446: THREE.Mesh
    keyboard_keyboard_0447: THREE.Mesh
    keyboard_keyboard_0448: THREE.Mesh
    keyboard_keyboard_0449: THREE.Mesh
    keyboard_keyboard_0450: THREE.Mesh
    keyboard_keyboard_0451: THREE.Mesh
    keyboard_keyboard_0452: THREE.Mesh
    keyboard_keyboard_0453: THREE.Mesh
    keyboard_keyboard_0454: THREE.Mesh
    keyboard_keyboard_0455: THREE.Mesh
    keyboard_keyboard_0456: THREE.Mesh
    keyboard_keyboard_0457: THREE.Mesh
    keyboard_keyboard_0458: THREE.Mesh
    keyboard_keyboard_0459: THREE.Mesh
    keyboard_keyboard_0460: THREE.Mesh
    keyboard_keyboard_0461: THREE.Mesh
    keyboard_keyboard_0462: THREE.Mesh
    keyboard_keyboard_0463: THREE.Mesh
    keyboard_keyboard_0464: THREE.Mesh
    keyboard_keyboard_0465: THREE.Mesh
    keyboard_keyboard_0466: THREE.Mesh
    keyboard_keyboard_0467: THREE.Mesh
    keyboard_keyboard_0468: THREE.Mesh
    keyboard_keyboard_0469: THREE.Mesh
    keyboard_keyboard_0470: THREE.Mesh
    keyboard_keyboard_0471: THREE.Mesh
    keyboard_keyboard_0472: THREE.Mesh
    keyboard_keyboard_0473: THREE.Mesh
    keyboard_keyboard_0474: THREE.Mesh
    keyboard_keyboard_0475: THREE.Mesh
    keyboard_keyboard_0476: THREE.Mesh
    keyboard_keyboard_0477: THREE.Mesh
    keyboard_keyboard_0478: THREE.Mesh
    keyboard_keyboard_0479: THREE.Mesh
    keyboard_keyboard_0480: THREE.Mesh
    keyboard_keyboard_0481: THREE.Mesh
    keyboard_keyboard_0482: THREE.Mesh
    keyboard_keyboard_0483: THREE.Mesh
    keyboard_keyboard_0484: THREE.Mesh
    keyboard_keyboard_0485: THREE.Mesh
    keyboard_keyboard_0486: THREE.Mesh
    keyboard_keyboard_0487: THREE.Mesh
    keyboard_keyboard_0488: THREE.Mesh
    keyboard_keyboard_0489: THREE.Mesh
    keyboard_keyboard_0490: THREE.Mesh
    keyboard_keyboard_0491: THREE.Mesh
    keyboard_keyboard_0492: THREE.Mesh
    keyboard_keyboard_0493: THREE.Mesh
    keyboard_keyboard_0494: THREE.Mesh
    keyboard_keyboard_0495: THREE.Mesh
    keyboard_keyboard_0496: THREE.Mesh
    keyboard_keyboard_0497: THREE.Mesh
    keyboard_keyboard_0498: THREE.Mesh
    keyboard_keyboard_0499: THREE.Mesh
    keyboard_keyboard_0500: THREE.Mesh
    keyboard_keyboard_0501: THREE.Mesh
    keyboard_keyboard_0502: THREE.Mesh
    keyboard_keyboard_0503: THREE.Mesh
    keyboard_keyboard_0504: THREE.Mesh
    keyboard_keyboard_0511: THREE.Mesh
    keyboard_keyboard_0512: THREE.Mesh
    keyboard_keyboard_0513: THREE.Mesh
    keyboard_keyboard_0514: THREE.Mesh
    keyboard_keyboard_0515: THREE.Mesh
    keyboard_keyboard_0516: THREE.Mesh
    keyboard_keyboard_0517: THREE.Mesh
    keyboard_keyboard_0518: THREE.Mesh
    keyboard_keyboard_0519: THREE.Mesh
    keyboard_keyboard_0520: THREE.Mesh
    keyboard_keyboard_0521: THREE.Mesh
    keyboard_keyboard_0522: THREE.Mesh
    keyboard_keyboard_0523: THREE.Mesh
    keyboard_keyboard_0524: THREE.Mesh
    keyboard_keyboard_0525: THREE.Mesh
    keyboard_keyboard_0526: THREE.Mesh
    keyboard_keyboard_0527: THREE.Mesh
    keyboard_keyboard_0528: THREE.Mesh
    keyboard_keyboard_0529: THREE.Mesh
    keyboard_keyboard_1: THREE.Mesh
    keyboard_keyboard_2: THREE.Mesh
    keyboard_keyboard_3: THREE.Mesh
    keyboard_keyboard_4: THREE.Mesh
    keyboard_keyboard_5: THREE.Mesh
    keyboard_keyboard_6: THREE.Mesh
    monitor_komponen_0: THREE.Mesh
    monitor_monitor_0: THREE.Mesh
    screen: THREE.Mesh
    mur_komponen_0: THREE.Mesh
    penyanggah_komponen_0: THREE.Mesh
    penyanggah001_komponen_0: THREE.Mesh
    penyanggah002_komponen_0: THREE.Mesh
    penyanggah003_komponen_0: THREE.Mesh
    penyanggah004_komponen_0: THREE.Mesh
    penyanggah005_komponen_0: THREE.Mesh
    penyanggah006_komponen_0: THREE.Mesh
    ssleaving_body_laptop_0: THREE.Mesh
  }
  materials: {
    body_laptop: THREE.MeshStandardMaterial
    komponen: THREE.MeshStandardMaterial
    hardware: THREE.MeshStandardMaterial
    keyboard: THREE.MeshStandardMaterial
    monitor: THREE.MeshStandardMaterial
    ['Material.001']: THREE.MeshStandardMaterial
  }
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/laptop-2.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group name="d41e0f029bbc4098ae68b375a3aa21d4fbx" scale={0.01}>
        <group name="keyboard" position={[-49.216, 28.549, 17.295]}>
          <mesh name="keyboard_keyboard_0" geometry={nodes.keyboard_keyboard_0.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_0001" geometry={nodes.keyboard_keyboard_0001.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_0002" geometry={nodes.keyboard_keyboard_0002.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_0003" geometry={nodes.keyboard_keyboard_0003.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_0004" geometry={nodes.keyboard_keyboard_0004.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_0005" geometry={nodes.keyboard_keyboard_0005.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_0006" geometry={nodes.keyboard_keyboard_0006.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_0007" geometry={nodes.keyboard_keyboard_0007.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_0008" geometry={nodes.keyboard_keyboard_0008.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_0009" geometry={nodes.keyboard_keyboard_0009.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_0010" geometry={nodes.keyboard_keyboard_0010.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_0011" geometry={nodes.keyboard_keyboard_0011.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_0012" geometry={nodes.keyboard_keyboard_0012.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_0013" geometry={nodes.keyboard_keyboard_0013.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_0014" geometry={nodes.keyboard_keyboard_0014.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_0015" geometry={nodes.keyboard_keyboard_0015.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_0016" geometry={nodes.keyboard_keyboard_0016.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_0017" geometry={nodes.keyboard_keyboard_0017.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_0018" geometry={nodes.keyboard_keyboard_0018.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_0019" geometry={nodes.keyboard_keyboard_0019.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_0020" geometry={nodes.keyboard_keyboard_0020.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_0021" geometry={nodes.keyboard_keyboard_0021.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_0022" geometry={nodes.keyboard_keyboard_0022.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_0023" geometry={nodes.keyboard_keyboard_0023.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_0024" geometry={nodes.keyboard_keyboard_0024.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_0025" geometry={nodes.keyboard_keyboard_0025.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_0026" geometry={nodes.keyboard_keyboard_0026.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_0027" geometry={nodes.keyboard_keyboard_0027.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_0028" geometry={nodes.keyboard_keyboard_0028.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_0029" geometry={nodes.keyboard_keyboard_0029.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_0030" geometry={nodes.keyboard_keyboard_0030.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_0031" geometry={nodes.keyboard_keyboard_0031.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_0032" geometry={nodes.keyboard_keyboard_0032.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_0033" geometry={nodes.keyboard_keyboard_0033.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_0034" geometry={nodes.keyboard_keyboard_0034.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_0035" geometry={nodes.keyboard_keyboard_0035.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_0036" geometry={nodes.keyboard_keyboard_0036.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_0037" geometry={nodes.keyboard_keyboard_0037.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_0038" geometry={nodes.keyboard_keyboard_0038.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_0039" geometry={nodes.keyboard_keyboard_0039.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_0040" geometry={nodes.keyboard_keyboard_0040.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_0041" geometry={nodes.keyboard_keyboard_0041.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_0042" geometry={nodes.keyboard_keyboard_0042.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_0043" geometry={nodes.keyboard_keyboard_0043.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_0044" geometry={nodes.keyboard_keyboard_0044.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_0045" geometry={nodes.keyboard_keyboard_0045.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_0046" geometry={nodes.keyboard_keyboard_0046.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_0047" geometry={nodes.keyboard_keyboard_0047.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_0048" geometry={nodes.keyboard_keyboard_0048.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_0049" geometry={nodes.keyboard_keyboard_0049.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_0050" geometry={nodes.keyboard_keyboard_0050.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_0051" geometry={nodes.keyboard_keyboard_0051.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_0052" geometry={nodes.keyboard_keyboard_0052.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_0053" geometry={nodes.keyboard_keyboard_0053.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_0054" geometry={nodes.keyboard_keyboard_0054.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_0055" geometry={nodes.keyboard_keyboard_0055.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_0056" geometry={nodes.keyboard_keyboard_0056.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_0057" geometry={nodes.keyboard_keyboard_0057.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_0058" geometry={nodes.keyboard_keyboard_0058.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_0059" geometry={nodes.keyboard_keyboard_0059.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_0060" geometry={nodes.keyboard_keyboard_0060.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_0061" geometry={nodes.keyboard_keyboard_0061.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_0062" geometry={nodes.keyboard_keyboard_0062.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_0063" geometry={nodes.keyboard_keyboard_0063.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_0064" geometry={nodes.keyboard_keyboard_0064.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_0065" geometry={nodes.keyboard_keyboard_0065.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_0066" geometry={nodes.keyboard_keyboard_0066.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_0067" geometry={nodes.keyboard_keyboard_0067.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_0068" geometry={nodes.keyboard_keyboard_0068.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_0069" geometry={nodes.keyboard_keyboard_0069.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_0070" geometry={nodes.keyboard_keyboard_0070.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_0071" geometry={nodes.keyboard_keyboard_0071.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_0072" geometry={nodes.keyboard_keyboard_0072.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_0073" geometry={nodes.keyboard_keyboard_0073.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_0074" geometry={nodes.keyboard_keyboard_0074.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_0075" geometry={nodes.keyboard_keyboard_0075.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_0076" geometry={nodes.keyboard_keyboard_0076.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_0077" geometry={nodes.keyboard_keyboard_0077.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_0078" geometry={nodes.keyboard_keyboard_0078.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_0079" geometry={nodes.keyboard_keyboard_0079.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_0080" geometry={nodes.keyboard_keyboard_0080.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_0081" geometry={nodes.keyboard_keyboard_0081.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_0082" geometry={nodes.keyboard_keyboard_0082.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_0083" geometry={nodes.keyboard_keyboard_0083.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_0084" geometry={nodes.keyboard_keyboard_0084.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_0085" geometry={nodes.keyboard_keyboard_0085.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_0086" geometry={nodes.keyboard_keyboard_0086.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_0087" geometry={nodes.keyboard_keyboard_0087.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_0088" geometry={nodes.keyboard_keyboard_0088.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_0089" geometry={nodes.keyboard_keyboard_0089.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_0090" geometry={nodes.keyboard_keyboard_0090.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_0091" geometry={nodes.keyboard_keyboard_0091.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_0092" geometry={nodes.keyboard_keyboard_0092.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_0093" geometry={nodes.keyboard_keyboard_0093.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_0094" geometry={nodes.keyboard_keyboard_0094.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_0095" geometry={nodes.keyboard_keyboard_0095.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_0096" geometry={nodes.keyboard_keyboard_0096.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_0097" geometry={nodes.keyboard_keyboard_0097.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_0098" geometry={nodes.keyboard_keyboard_0098.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_0099" geometry={nodes.keyboard_keyboard_0099.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_0100" geometry={nodes.keyboard_keyboard_0100.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_0101" geometry={nodes.keyboard_keyboard_0101.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_0102" geometry={nodes.keyboard_keyboard_0102.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_0103" geometry={nodes.keyboard_keyboard_0103.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_0104" geometry={nodes.keyboard_keyboard_0104.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_0105" geometry={nodes.keyboard_keyboard_0105.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_0106" geometry={nodes.keyboard_keyboard_0106.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_0107" geometry={nodes.keyboard_keyboard_0107.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_0108" geometry={nodes.keyboard_keyboard_0108.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_0109" geometry={nodes.keyboard_keyboard_0109.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_0110" geometry={nodes.keyboard_keyboard_0110.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_0111" geometry={nodes.keyboard_keyboard_0111.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_0112" geometry={nodes.keyboard_keyboard_0112.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_0113" geometry={nodes.keyboard_keyboard_0113.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_0114" geometry={nodes.keyboard_keyboard_0114.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_0115" geometry={nodes.keyboard_keyboard_0115.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_0116" geometry={nodes.keyboard_keyboard_0116.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_0117" geometry={nodes.keyboard_keyboard_0117.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_0118" geometry={nodes.keyboard_keyboard_0118.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_0119" geometry={nodes.keyboard_keyboard_0119.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_0120" geometry={nodes.keyboard_keyboard_0120.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_0121" geometry={nodes.keyboard_keyboard_0121.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_0122" geometry={nodes.keyboard_keyboard_0122.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_0123" geometry={nodes.keyboard_keyboard_0123.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_0124" geometry={nodes.keyboard_keyboard_0124.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_0125" geometry={nodes.keyboard_keyboard_0125.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_0126" geometry={nodes.keyboard_keyboard_0126.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_0127" geometry={nodes.keyboard_keyboard_0127.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_0128" geometry={nodes.keyboard_keyboard_0128.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_0129" geometry={nodes.keyboard_keyboard_0129.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_0130" geometry={nodes.keyboard_keyboard_0130.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_0131" geometry={nodes.keyboard_keyboard_0131.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_0132" geometry={nodes.keyboard_keyboard_0132.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_0133" geometry={nodes.keyboard_keyboard_0133.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_0134" geometry={nodes.keyboard_keyboard_0134.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_0135" geometry={nodes.keyboard_keyboard_0135.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_0136" geometry={nodes.keyboard_keyboard_0136.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_0137" geometry={nodes.keyboard_keyboard_0137.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_0138" geometry={nodes.keyboard_keyboard_0138.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_0139" geometry={nodes.keyboard_keyboard_0139.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_0140" geometry={nodes.keyboard_keyboard_0140.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_0141" geometry={nodes.keyboard_keyboard_0141.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_0142" geometry={nodes.keyboard_keyboard_0142.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_0143" geometry={nodes.keyboard_keyboard_0143.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_0144" geometry={nodes.keyboard_keyboard_0144.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_0145" geometry={nodes.keyboard_keyboard_0145.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_0146" geometry={nodes.keyboard_keyboard_0146.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_0147" geometry={nodes.keyboard_keyboard_0147.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_0148" geometry={nodes.keyboard_keyboard_0148.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_0149" geometry={nodes.keyboard_keyboard_0149.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_0150" geometry={nodes.keyboard_keyboard_0150.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_0151" geometry={nodes.keyboard_keyboard_0151.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_0152" geometry={nodes.keyboard_keyboard_0152.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_0153" geometry={nodes.keyboard_keyboard_0153.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_0154" geometry={nodes.keyboard_keyboard_0154.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_0155" geometry={nodes.keyboard_keyboard_0155.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_0156" geometry={nodes.keyboard_keyboard_0156.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_0157" geometry={nodes.keyboard_keyboard_0157.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_0158" geometry={nodes.keyboard_keyboard_0158.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_0159" geometry={nodes.keyboard_keyboard_0159.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_0160" geometry={nodes.keyboard_keyboard_0160.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_0161" geometry={nodes.keyboard_keyboard_0161.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_0162" geometry={nodes.keyboard_keyboard_0162.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_0163" geometry={nodes.keyboard_keyboard_0163.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_0164" geometry={nodes.keyboard_keyboard_0164.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_0165" geometry={nodes.keyboard_keyboard_0165.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_0166" geometry={nodes.keyboard_keyboard_0166.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_0167" geometry={nodes.keyboard_keyboard_0167.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_0168" geometry={nodes.keyboard_keyboard_0168.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_0169" geometry={nodes.keyboard_keyboard_0169.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_0170" geometry={nodes.keyboard_keyboard_0170.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_0171" geometry={nodes.keyboard_keyboard_0171.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_0172" geometry={nodes.keyboard_keyboard_0172.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_0173" geometry={nodes.keyboard_keyboard_0173.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_0174" geometry={nodes.keyboard_keyboard_0174.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_0175" geometry={nodes.keyboard_keyboard_0175.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_0176" geometry={nodes.keyboard_keyboard_0176.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_0177" geometry={nodes.keyboard_keyboard_0177.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_0178" geometry={nodes.keyboard_keyboard_0178.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_0179" geometry={nodes.keyboard_keyboard_0179.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_0180" geometry={nodes.keyboard_keyboard_0180.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_0181" geometry={nodes.keyboard_keyboard_0181.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_0182" geometry={nodes.keyboard_keyboard_0182.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_0183" geometry={nodes.keyboard_keyboard_0183.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_0184" geometry={nodes.keyboard_keyboard_0184.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_0185" geometry={nodes.keyboard_keyboard_0185.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_0186" geometry={nodes.keyboard_keyboard_0186.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_0187" geometry={nodes.keyboard_keyboard_0187.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_0188" geometry={nodes.keyboard_keyboard_0188.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_0189" geometry={nodes.keyboard_keyboard_0189.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_0190" geometry={nodes.keyboard_keyboard_0190.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_0191" geometry={nodes.keyboard_keyboard_0191.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_0192" geometry={nodes.keyboard_keyboard_0192.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_0193" geometry={nodes.keyboard_keyboard_0193.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_0194" geometry={nodes.keyboard_keyboard_0194.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_0195" geometry={nodes.keyboard_keyboard_0195.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_0196" geometry={nodes.keyboard_keyboard_0196.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_0197" geometry={nodes.keyboard_keyboard_0197.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_0198" geometry={nodes.keyboard_keyboard_0198.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_0199" geometry={nodes.keyboard_keyboard_0199.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_0200" geometry={nodes.keyboard_keyboard_0200.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_0201" geometry={nodes.keyboard_keyboard_0201.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_0202" geometry={nodes.keyboard_keyboard_0202.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_0203" geometry={nodes.keyboard_keyboard_0203.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_0204" geometry={nodes.keyboard_keyboard_0204.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_0205" geometry={nodes.keyboard_keyboard_0205.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_0206" geometry={nodes.keyboard_keyboard_0206.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_0207" geometry={nodes.keyboard_keyboard_0207.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_0208" geometry={nodes.keyboard_keyboard_0208.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_0209" geometry={nodes.keyboard_keyboard_0209.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_0210" geometry={nodes.keyboard_keyboard_0210.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_0211" geometry={nodes.keyboard_keyboard_0211.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_0212" geometry={nodes.keyboard_keyboard_0212.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_0213" geometry={nodes.keyboard_keyboard_0213.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_0214" geometry={nodes.keyboard_keyboard_0214.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_0215" geometry={nodes.keyboard_keyboard_0215.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_0216" geometry={nodes.keyboard_keyboard_0216.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_0217" geometry={nodes.keyboard_keyboard_0217.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_0218" geometry={nodes.keyboard_keyboard_0218.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_0219" geometry={nodes.keyboard_keyboard_0219.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_0220" geometry={nodes.keyboard_keyboard_0220.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_0221" geometry={nodes.keyboard_keyboard_0221.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_0222" geometry={nodes.keyboard_keyboard_0222.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_0223" geometry={nodes.keyboard_keyboard_0223.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_0224" geometry={nodes.keyboard_keyboard_0224.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_0225" geometry={nodes.keyboard_keyboard_0225.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_0226" geometry={nodes.keyboard_keyboard_0226.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_0227" geometry={nodes.keyboard_keyboard_0227.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_0228" geometry={nodes.keyboard_keyboard_0228.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_0229" geometry={nodes.keyboard_keyboard_0229.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_0230" geometry={nodes.keyboard_keyboard_0230.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_0231" geometry={nodes.keyboard_keyboard_0231.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_0232" geometry={nodes.keyboard_keyboard_0232.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_0233" geometry={nodes.keyboard_keyboard_0233.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_0234" geometry={nodes.keyboard_keyboard_0234.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_0235" geometry={nodes.keyboard_keyboard_0235.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_0236" geometry={nodes.keyboard_keyboard_0236.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_0237" geometry={nodes.keyboard_keyboard_0237.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_0238" geometry={nodes.keyboard_keyboard_0238.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_0239" geometry={nodes.keyboard_keyboard_0239.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_0240" geometry={nodes.keyboard_keyboard_0240.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_0241" geometry={nodes.keyboard_keyboard_0241.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_0242" geometry={nodes.keyboard_keyboard_0242.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_0243" geometry={nodes.keyboard_keyboard_0243.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_0244" geometry={nodes.keyboard_keyboard_0244.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_0245" geometry={nodes.keyboard_keyboard_0245.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_0246" geometry={nodes.keyboard_keyboard_0246.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_0247" geometry={nodes.keyboard_keyboard_0247.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_0248" geometry={nodes.keyboard_keyboard_0248.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_0249" geometry={nodes.keyboard_keyboard_0249.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_0250" geometry={nodes.keyboard_keyboard_0250.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_0251" geometry={nodes.keyboard_keyboard_0251.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_0252" geometry={nodes.keyboard_keyboard_0252.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_0253" geometry={nodes.keyboard_keyboard_0253.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_0254" geometry={nodes.keyboard_keyboard_0254.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_0255" geometry={nodes.keyboard_keyboard_0255.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_0256" geometry={nodes.keyboard_keyboard_0256.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_0257" geometry={nodes.keyboard_keyboard_0257.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_0258" geometry={nodes.keyboard_keyboard_0258.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_0259" geometry={nodes.keyboard_keyboard_0259.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_0260" geometry={nodes.keyboard_keyboard_0260.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_0261" geometry={nodes.keyboard_keyboard_0261.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_0262" geometry={nodes.keyboard_keyboard_0262.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_0263" geometry={nodes.keyboard_keyboard_0263.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_0264" geometry={nodes.keyboard_keyboard_0264.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_0265" geometry={nodes.keyboard_keyboard_0265.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_0266" geometry={nodes.keyboard_keyboard_0266.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_0267" geometry={nodes.keyboard_keyboard_0267.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_0268" geometry={nodes.keyboard_keyboard_0268.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_0269" geometry={nodes.keyboard_keyboard_0269.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_0270" geometry={nodes.keyboard_keyboard_0270.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_0271" geometry={nodes.keyboard_keyboard_0271.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_0272" geometry={nodes.keyboard_keyboard_0272.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_0273" geometry={nodes.keyboard_keyboard_0273.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_0274" geometry={nodes.keyboard_keyboard_0274.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_0275" geometry={nodes.keyboard_keyboard_0275.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_0276" geometry={nodes.keyboard_keyboard_0276.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_0277" geometry={nodes.keyboard_keyboard_0277.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_0278" geometry={nodes.keyboard_keyboard_0278.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_0279" geometry={nodes.keyboard_keyboard_0279.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_0280" geometry={nodes.keyboard_keyboard_0280.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_0281" geometry={nodes.keyboard_keyboard_0281.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_0282" geometry={nodes.keyboard_keyboard_0282.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_0283" geometry={nodes.keyboard_keyboard_0283.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_0284" geometry={nodes.keyboard_keyboard_0284.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_0285" geometry={nodes.keyboard_keyboard_0285.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_0286" geometry={nodes.keyboard_keyboard_0286.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_0287" geometry={nodes.keyboard_keyboard_0287.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_0288" geometry={nodes.keyboard_keyboard_0288.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_0289" geometry={nodes.keyboard_keyboard_0289.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_0290" geometry={nodes.keyboard_keyboard_0290.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_0291" geometry={nodes.keyboard_keyboard_0291.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_0292" geometry={nodes.keyboard_keyboard_0292.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_0293" geometry={nodes.keyboard_keyboard_0293.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_0294" geometry={nodes.keyboard_keyboard_0294.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_0295" geometry={nodes.keyboard_keyboard_0295.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_0296" geometry={nodes.keyboard_keyboard_0296.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_0297" geometry={nodes.keyboard_keyboard_0297.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_0298" geometry={nodes.keyboard_keyboard_0298.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_0299" geometry={nodes.keyboard_keyboard_0299.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_0300" geometry={nodes.keyboard_keyboard_0300.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_0301" geometry={nodes.keyboard_keyboard_0301.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_0302" geometry={nodes.keyboard_keyboard_0302.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_0303" geometry={nodes.keyboard_keyboard_0303.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_0304" geometry={nodes.keyboard_keyboard_0304.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_0305" geometry={nodes.keyboard_keyboard_0305.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_0306" geometry={nodes.keyboard_keyboard_0306.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_0307" geometry={nodes.keyboard_keyboard_0307.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_0308" geometry={nodes.keyboard_keyboard_0308.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_0309" geometry={nodes.keyboard_keyboard_0309.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_0310" geometry={nodes.keyboard_keyboard_0310.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_0311" geometry={nodes.keyboard_keyboard_0311.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_0312" geometry={nodes.keyboard_keyboard_0312.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_0313" geometry={nodes.keyboard_keyboard_0313.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_0314" geometry={nodes.keyboard_keyboard_0314.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_0315" geometry={nodes.keyboard_keyboard_0315.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_0316" geometry={nodes.keyboard_keyboard_0316.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_0317" geometry={nodes.keyboard_keyboard_0317.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_0318" geometry={nodes.keyboard_keyboard_0318.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_0319" geometry={nodes.keyboard_keyboard_0319.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_0320" geometry={nodes.keyboard_keyboard_0320.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_0321" geometry={nodes.keyboard_keyboard_0321.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_0322" geometry={nodes.keyboard_keyboard_0322.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_0323" geometry={nodes.keyboard_keyboard_0323.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_0324" geometry={nodes.keyboard_keyboard_0324.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_0325" geometry={nodes.keyboard_keyboard_0325.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_0326" geometry={nodes.keyboard_keyboard_0326.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_0327" geometry={nodes.keyboard_keyboard_0327.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_0328" geometry={nodes.keyboard_keyboard_0328.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_0329" geometry={nodes.keyboard_keyboard_0329.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_0330" geometry={nodes.keyboard_keyboard_0330.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_0331" geometry={nodes.keyboard_keyboard_0331.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_0332" geometry={nodes.keyboard_keyboard_0332.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_0333" geometry={nodes.keyboard_keyboard_0333.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_0334" geometry={nodes.keyboard_keyboard_0334.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_0335" geometry={nodes.keyboard_keyboard_0335.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_0336" geometry={nodes.keyboard_keyboard_0336.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_0337" geometry={nodes.keyboard_keyboard_0337.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_0338" geometry={nodes.keyboard_keyboard_0338.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_0339" geometry={nodes.keyboard_keyboard_0339.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_0340" geometry={nodes.keyboard_keyboard_0340.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_0341" geometry={nodes.keyboard_keyboard_0341.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_0342" geometry={nodes.keyboard_keyboard_0342.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_0343" geometry={nodes.keyboard_keyboard_0343.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_0344" geometry={nodes.keyboard_keyboard_0344.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_0345" geometry={nodes.keyboard_keyboard_0345.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_0346" geometry={nodes.keyboard_keyboard_0346.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_0347" geometry={nodes.keyboard_keyboard_0347.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_0348" geometry={nodes.keyboard_keyboard_0348.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_0349" geometry={nodes.keyboard_keyboard_0349.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_0350" geometry={nodes.keyboard_keyboard_0350.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_0351" geometry={nodes.keyboard_keyboard_0351.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_0352" geometry={nodes.keyboard_keyboard_0352.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_0353" geometry={nodes.keyboard_keyboard_0353.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_0354" geometry={nodes.keyboard_keyboard_0354.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_0355" geometry={nodes.keyboard_keyboard_0355.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_0356" geometry={nodes.keyboard_keyboard_0356.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_0357" geometry={nodes.keyboard_keyboard_0357.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_0358" geometry={nodes.keyboard_keyboard_0358.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_0359" geometry={nodes.keyboard_keyboard_0359.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_0360" geometry={nodes.keyboard_keyboard_0360.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_0361" geometry={nodes.keyboard_keyboard_0361.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_0362" geometry={nodes.keyboard_keyboard_0362.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_0363" geometry={nodes.keyboard_keyboard_0363.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_0364" geometry={nodes.keyboard_keyboard_0364.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_0365" geometry={nodes.keyboard_keyboard_0365.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_0366" geometry={nodes.keyboard_keyboard_0366.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_0367" geometry={nodes.keyboard_keyboard_0367.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_0368" geometry={nodes.keyboard_keyboard_0368.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_0369" geometry={nodes.keyboard_keyboard_0369.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_0370" geometry={nodes.keyboard_keyboard_0370.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_0371" geometry={nodes.keyboard_keyboard_0371.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_0372" geometry={nodes.keyboard_keyboard_0372.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_0373" geometry={nodes.keyboard_keyboard_0373.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_0374" geometry={nodes.keyboard_keyboard_0374.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_0375" geometry={nodes.keyboard_keyboard_0375.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_0376" geometry={nodes.keyboard_keyboard_0376.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_0377" geometry={nodes.keyboard_keyboard_0377.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_0378" geometry={nodes.keyboard_keyboard_0378.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_0379" geometry={nodes.keyboard_keyboard_0379.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_0380" geometry={nodes.keyboard_keyboard_0380.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_0381" geometry={nodes.keyboard_keyboard_0381.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_0382" geometry={nodes.keyboard_keyboard_0382.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_0383" geometry={nodes.keyboard_keyboard_0383.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_0384" geometry={nodes.keyboard_keyboard_0384.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_0385" geometry={nodes.keyboard_keyboard_0385.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_0386" geometry={nodes.keyboard_keyboard_0386.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_0387" geometry={nodes.keyboard_keyboard_0387.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_0388" geometry={nodes.keyboard_keyboard_0388.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_0389" geometry={nodes.keyboard_keyboard_0389.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_0390" geometry={nodes.keyboard_keyboard_0390.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_0391" geometry={nodes.keyboard_keyboard_0391.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_0392" geometry={nodes.keyboard_keyboard_0392.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_0393" geometry={nodes.keyboard_keyboard_0393.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_0394" geometry={nodes.keyboard_keyboard_0394.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_0395" geometry={nodes.keyboard_keyboard_0395.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_0396" geometry={nodes.keyboard_keyboard_0396.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_0397" geometry={nodes.keyboard_keyboard_0397.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_0398" geometry={nodes.keyboard_keyboard_0398.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_0399" geometry={nodes.keyboard_keyboard_0399.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_0400" geometry={nodes.keyboard_keyboard_0400.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_0401" geometry={nodes.keyboard_keyboard_0401.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_0402" geometry={nodes.keyboard_keyboard_0402.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_0403" geometry={nodes.keyboard_keyboard_0403.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_0404" geometry={nodes.keyboard_keyboard_0404.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_0405" geometry={nodes.keyboard_keyboard_0405.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_0406" geometry={nodes.keyboard_keyboard_0406.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_0407" geometry={nodes.keyboard_keyboard_0407.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_0408" geometry={nodes.keyboard_keyboard_0408.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_0409" geometry={nodes.keyboard_keyboard_0409.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_0410" geometry={nodes.keyboard_keyboard_0410.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_0411" geometry={nodes.keyboard_keyboard_0411.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_0412" geometry={nodes.keyboard_keyboard_0412.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_0413" geometry={nodes.keyboard_keyboard_0413.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_0414" geometry={nodes.keyboard_keyboard_0414.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_0415" geometry={nodes.keyboard_keyboard_0415.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_0416" geometry={nodes.keyboard_keyboard_0416.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_0417" geometry={nodes.keyboard_keyboard_0417.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_0418" geometry={nodes.keyboard_keyboard_0418.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_0419" geometry={nodes.keyboard_keyboard_0419.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_0420" geometry={nodes.keyboard_keyboard_0420.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_0421" geometry={nodes.keyboard_keyboard_0421.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_0422" geometry={nodes.keyboard_keyboard_0422.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_0423" geometry={nodes.keyboard_keyboard_0423.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_0424" geometry={nodes.keyboard_keyboard_0424.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_0425" geometry={nodes.keyboard_keyboard_0425.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_0426" geometry={nodes.keyboard_keyboard_0426.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_0427" geometry={nodes.keyboard_keyboard_0427.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_0428" geometry={nodes.keyboard_keyboard_0428.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_0429" geometry={nodes.keyboard_keyboard_0429.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_0430" geometry={nodes.keyboard_keyboard_0430.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_0431" geometry={nodes.keyboard_keyboard_0431.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_0432" geometry={nodes.keyboard_keyboard_0432.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_0433" geometry={nodes.keyboard_keyboard_0433.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_0434" geometry={nodes.keyboard_keyboard_0434.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_0435" geometry={nodes.keyboard_keyboard_0435.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_0436" geometry={nodes.keyboard_keyboard_0436.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_0437" geometry={nodes.keyboard_keyboard_0437.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_0438" geometry={nodes.keyboard_keyboard_0438.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_0439" geometry={nodes.keyboard_keyboard_0439.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_0440" geometry={nodes.keyboard_keyboard_0440.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_0441" geometry={nodes.keyboard_keyboard_0441.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_0442" geometry={nodes.keyboard_keyboard_0442.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_0443" geometry={nodes.keyboard_keyboard_0443.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_0444" geometry={nodes.keyboard_keyboard_0444.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_0445" geometry={nodes.keyboard_keyboard_0445.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_0446" geometry={nodes.keyboard_keyboard_0446.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_0447" geometry={nodes.keyboard_keyboard_0447.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_0448" geometry={nodes.keyboard_keyboard_0448.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_0449" geometry={nodes.keyboard_keyboard_0449.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_0450" geometry={nodes.keyboard_keyboard_0450.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_0451" geometry={nodes.keyboard_keyboard_0451.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_0452" geometry={nodes.keyboard_keyboard_0452.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_0453" geometry={nodes.keyboard_keyboard_0453.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_0454" geometry={nodes.keyboard_keyboard_0454.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_0455" geometry={nodes.keyboard_keyboard_0455.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_0456" geometry={nodes.keyboard_keyboard_0456.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_0457" geometry={nodes.keyboard_keyboard_0457.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_0458" geometry={nodes.keyboard_keyboard_0458.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_0459" geometry={nodes.keyboard_keyboard_0459.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_0460" geometry={nodes.keyboard_keyboard_0460.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_0461" geometry={nodes.keyboard_keyboard_0461.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_0462" geometry={nodes.keyboard_keyboard_0462.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_0463" geometry={nodes.keyboard_keyboard_0463.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_0464" geometry={nodes.keyboard_keyboard_0464.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_0465" geometry={nodes.keyboard_keyboard_0465.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_0466" geometry={nodes.keyboard_keyboard_0466.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_0467" geometry={nodes.keyboard_keyboard_0467.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_0468" geometry={nodes.keyboard_keyboard_0468.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_0469" geometry={nodes.keyboard_keyboard_0469.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_0470" geometry={nodes.keyboard_keyboard_0470.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_0471" geometry={nodes.keyboard_keyboard_0471.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_0472" geometry={nodes.keyboard_keyboard_0472.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_0473" geometry={nodes.keyboard_keyboard_0473.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_0474" geometry={nodes.keyboard_keyboard_0474.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_0475" geometry={nodes.keyboard_keyboard_0475.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_0476" geometry={nodes.keyboard_keyboard_0476.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_0477" geometry={nodes.keyboard_keyboard_0477.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_0478" geometry={nodes.keyboard_keyboard_0478.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_0479" geometry={nodes.keyboard_keyboard_0479.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_0480" geometry={nodes.keyboard_keyboard_0480.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_0481" geometry={nodes.keyboard_keyboard_0481.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_0482" geometry={nodes.keyboard_keyboard_0482.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_0483" geometry={nodes.keyboard_keyboard_0483.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_0484" geometry={nodes.keyboard_keyboard_0484.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_0485" geometry={nodes.keyboard_keyboard_0485.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_0486" geometry={nodes.keyboard_keyboard_0486.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_0487" geometry={nodes.keyboard_keyboard_0487.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_0488" geometry={nodes.keyboard_keyboard_0488.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_0489" geometry={nodes.keyboard_keyboard_0489.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_0490" geometry={nodes.keyboard_keyboard_0490.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_0491" geometry={nodes.keyboard_keyboard_0491.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_0492" geometry={nodes.keyboard_keyboard_0492.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_0493" geometry={nodes.keyboard_keyboard_0493.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_0494" geometry={nodes.keyboard_keyboard_0494.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_0495" geometry={nodes.keyboard_keyboard_0495.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_0496" geometry={nodes.keyboard_keyboard_0496.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_0497" geometry={nodes.keyboard_keyboard_0497.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_0498" geometry={nodes.keyboard_keyboard_0498.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_0499" geometry={nodes.keyboard_keyboard_0499.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_0500" geometry={nodes.keyboard_keyboard_0500.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_0501" geometry={nodes.keyboard_keyboard_0501.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_0502" geometry={nodes.keyboard_keyboard_0502.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_0503" geometry={nodes.keyboard_keyboard_0503.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_0504" geometry={nodes.keyboard_keyboard_0504.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_0511" geometry={nodes.keyboard_keyboard_0511.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_0512" geometry={nodes.keyboard_keyboard_0512.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_0513" geometry={nodes.keyboard_keyboard_0513.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_0514" geometry={nodes.keyboard_keyboard_0514.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_0515" geometry={nodes.keyboard_keyboard_0515.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_0516" geometry={nodes.keyboard_keyboard_0516.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_0517" geometry={nodes.keyboard_keyboard_0517.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_0518" geometry={nodes.keyboard_keyboard_0518.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_0519" geometry={nodes.keyboard_keyboard_0519.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_0520" geometry={nodes.keyboard_keyboard_0520.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_0521" geometry={nodes.keyboard_keyboard_0521.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_0522" geometry={nodes.keyboard_keyboard_0522.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_0523" geometry={nodes.keyboard_keyboard_0523.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_0524" geometry={nodes.keyboard_keyboard_0524.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_0525" geometry={nodes.keyboard_keyboard_0525.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_0526" geometry={nodes.keyboard_keyboard_0526.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_0527" geometry={nodes.keyboard_keyboard_0527.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_0528" geometry={nodes.keyboard_keyboard_0528.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_0529" geometry={nodes.keyboard_keyboard_0529.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_1" geometry={nodes.keyboard_keyboard_1.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_2" geometry={nodes.keyboard_keyboard_2.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_3" geometry={nodes.keyboard_keyboard_3.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_4" geometry={nodes.keyboard_keyboard_4.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_5" geometry={nodes.keyboard_keyboard_5.geometry} material={materials.keyboard} />
          <mesh name="keyboard_keyboard_6" geometry={nodes.keyboard_keyboard_6.geometry} material={materials.keyboard} />
        </group>
        <group name="monitor" position={[-222.962, 30.61, -137.743]} rotation={[-0.36, 0, 0]}>
          <mesh name="monitor_komponen_0" geometry={nodes.monitor_komponen_0.geometry} material={materials.komponen} />
          <mesh name="monitor_monitor_0" geometry={nodes.monitor_monitor_0.geometry} material={materials.monitor} />
          <mesh name="screen" geometry={nodes.screen.geometry} material={materials['Material.001']} />
        </group>
        <mesh name="body_laptop_body_laptop_0" geometry={nodes.body_laptop_body_laptop_0.geometry} material={materials.body_laptop} position={[0, 15.353, 0]} />
        <mesh name="conncector_komponen_0" geometry={nodes.conncector_komponen_0.geometry} material={materials.komponen} position={[217.118, 24.696, 42.333]} />
        <mesh name="cover_bawah_komponen_0" geometry={nodes.cover_bawah_komponen_0.geometry} material={materials.komponen} position={[0, 15.31, 0]} />
        <mesh name="hardware_hardware_0" geometry={nodes.hardware_hardware_0.geometry} material={materials.hardware} position={[0, 13.429, 0]} />
        <mesh name="mur_komponen_0" geometry={nodes.mur_komponen_0.geometry} material={materials.komponen} position={[199.762, 12.895, -155.177]} />
        <mesh name="penyanggah_komponen_0" geometry={nodes.penyanggah_komponen_0.geometry} material={materials.komponen} position={[55.636, 3.506, -139.125]} />
        <mesh name="penyanggah001_komponen_0" geometry={nodes.penyanggah001_komponen_0.geometry} material={materials.komponen} position={[63.12, 4.042, -20.352]} />
        <mesh name="penyanggah002_komponen_0" geometry={nodes.penyanggah002_komponen_0.geometry} material={materials.komponen} position={[-120.181, 3.897, -24.696]} />
        <mesh name="penyanggah003_komponen_0" geometry={nodes.penyanggah003_komponen_0.geometry} material={materials.komponen} position={[-188.035, 9.362, 126.206]} />
        <mesh name="penyanggah004_komponen_0" geometry={nodes.penyanggah004_komponen_0.geometry} material={materials.komponen} position={[-17.139, 9.362, 138.2]} />
        <mesh name="penyanggah005_komponen_0" geometry={nodes.penyanggah005_komponen_0.geometry} material={materials.komponen} position={[165.282, 9.362, 126.206]} />
        <mesh name="penyanggah006_komponen_0" geometry={nodes.penyanggah006_komponen_0.geometry} material={materials.komponen} position={[-158.465, 3.248, -127.506]} />
        <mesh name="ssleaving_body_laptop_0" geometry={nodes.ssleaving_body_laptop_0.geometry} material={materials.body_laptop} position={[0, 15.353, 0]} />
      </group>
    </group>
  )
}

useGLTF.preload('/laptop-2.glb')
