"use client";

import { Text } from "@react-three/drei";
import {
  GetRecentlyPlayedSongRequest,
  GetRecentlyPlayedSongResponse,
} from "@amirsalarsafaei/autogenerated/playground/spotify";
import * as THREE from "three";
import { useLoader } from "@react-three/fiber";
import { Suspense, useEffect, useMemo, useState } from "react";
import { useGrpc } from "@/providers/GrpcProvider";
import DivoomSpeakerModel from "@/models/DivoomSpeakerModel";

// How long to wait before reopening the now-playing stream after it drops.
const RESUBSCRIBE_DELAY = 5_000;

const pixelateVertexShader = `
  varying vec2 vUv;
  
  void main() {
    vUv = uv;
    gl_Position = projectionMatrix * modelViewMatrix * vec4(position, 1.0);
  }
`;

const pixelateFragmentShader = `
  uniform sampler2D uTexture;
  uniform float uPixelSize;
  varying vec2 vUv;
  
  void main() {
    vec2 pixelatedUv = floor(vUv * uPixelSize) / uPixelSize;
    gl_FragColor = texture2D(uTexture, pixelatedUv);
  }
`;

function AlbumArt({ url }: { url: string }) {
  // TODO: surely pixelating a jpeg can be done without custom shaders.
  const pixelMaterial = useMemo(() => {
    const texture = useLoader(THREE.TextureLoader, url);
    return new THREE.ShaderMaterial({
      uniforms: {
        uTexture: { value: texture },
        uPixelSize: { value: 16 },
      },
      vertexShader: pixelateVertexShader,
      fragmentShader: pixelateFragmentShader,
      transparent: true,
    });
  }, [url]);

  return (
    <mesh position={[0, 0.6, 0.85]}>
      <planeGeometry args={[2.7, 2.7]} />
      <primitive object={pixelMaterial} attach="material" />
    </mesh>
  );
}

export default function MusicPlayer() {
  const { spotify_client } = useGrpc();

  const [data, setData] = useState<GetRecentlyPlayedSongResponse | undefined>();
  const [status, setStatus] = useState<"pending" | "error" | "success">(
    "pending",
  );

  // Subscribe to the live now-playing stream: the backend pushes the current
  // track immediately and then on every change, so there's no polling. The
  // subscription is torn down on unmount and reopened on transient drops.
  useEffect(() => {
    let active = true;
    let subscription: { unsubscribe: () => void } | undefined;
    let retry: ReturnType<typeof setTimeout> | undefined;

    const subscribe = () => {
      if (!active) return;
      const request = GetRecentlyPlayedSongRequest.create();
      subscription = spotify_client
        .StreamRecentlyPlayedSong(request)
        .subscribe({
          next: (song) => {
            setData(song);
            setStatus("success");
          },
          error: (err) => {
            console.error("Spotify stream error:", err);
            if (!active) return;
            // Keep showing the last track if we already had one.
            setStatus((s) => (s === "success" ? s : "error"));
            retry = setTimeout(subscribe, RESUBSCRIBE_DELAY);
          },
          complete: () => {
            if (active) retry = setTimeout(subscribe, RESUBSCRIBE_DELAY);
          },
        });
    };

    subscribe();

    return () => {
      active = false;
      subscription?.unsubscribe();
      if (retry) clearTimeout(retry);
    };
  }, [spotify_client]);

  const isPending = status === "pending";
  const isLoadingError = status === "error";
  const isSuccess = status === "success";

  return (
    <group
      rotation={[0, -Math.PI / 6, 0]}
      position={[11.1, 0, -0.2]}
      scale={1.25}
    >
      <DivoomSpeakerModel
        rotation={[0, Math.PI / 2, 0]}
        renderOrder={1}
        customDepth={{
          depthWrite: false,
          depthTest: true,
        }}
      />

      <group position={[0, 2, -0.18]} scale={0.7} rotation={[-0.1, 0, 0]}>
        <Suspense fallback={null}>
          {isPending || isLoadingError ? (
            <Text
              color="#FF2E2E"
              scale={0.3}
              position={[0, 2, 1.05]}
              maxWidth={13}
              textAlign="center"
              anchorX="center"
              anchorY="top"
            >
              {isPending ? "Loading" : "Error"}
            </Text>
          ) : (
            <>
              <Text
                color="#00FFFF"
                scale={0.3}
                position={[0, 2.6, 1.2]}
                maxWidth={13}
                textAlign="center"
                anchorX="center"
                anchorY="top"
                font="Signika-Medium.ttf"
              >
                {data?.playing
                  ? "Playing on Spotify"
                  : "Last played on Spotify"}
              </Text>
              {data?.albumArtUrl && <AlbumArt url={data.albumArtUrl} />}
              <Text
                color="#00FFFF"
                scale={0.3}
                position={[0, 0.05, 0.87]}
                maxWidth={13}
                textAlign="center"
                anchorX="center"
                anchorY="top"
                overflowWrap="break-word"
                whiteSpace="normal"
                font="Signika-Medium.ttf"
              >
                {isSuccess && data ? `${data.track}\n${data.artist}` : ""}
              </Text>
            </>
          )}
        </Suspense>
      </group>
    </group>
  );
}
