// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: playground/spotify.proto

package playground

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Spotify_GetRecentlyPlayedSong_FullMethodName = "/playground.Spotify/GetRecentlyPlayedSong"
)

// SpotifyClient is the client API for Spotify service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SpotifyClient interface {
	GetRecentlyPlayedSong(ctx context.Context, in *GetRecentlyPlayedSongRequest, opts ...grpc.CallOption) (*GetRecentlyPlayedSongResponse, error)
}

type spotifyClient struct {
	cc grpc.ClientConnInterface
}

func NewSpotifyClient(cc grpc.ClientConnInterface) SpotifyClient {
	return &spotifyClient{cc}
}

func (c *spotifyClient) GetRecentlyPlayedSong(ctx context.Context, in *GetRecentlyPlayedSongRequest, opts ...grpc.CallOption) (*GetRecentlyPlayedSongResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetRecentlyPlayedSongResponse)
	err := c.cc.Invoke(ctx, Spotify_GetRecentlyPlayedSong_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SpotifyServer is the server API for Spotify service.
// All implementations must embed UnimplementedSpotifyServer
// for forward compatibility.
type SpotifyServer interface {
	GetRecentlyPlayedSong(context.Context, *GetRecentlyPlayedSongRequest) (*GetRecentlyPlayedSongResponse, error)
	mustEmbedUnimplementedSpotifyServer()
}

// UnimplementedSpotifyServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSpotifyServer struct{}

func (UnimplementedSpotifyServer) GetRecentlyPlayedSong(context.Context, *GetRecentlyPlayedSongRequest) (*GetRecentlyPlayedSongResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetRecentlyPlayedSong not implemented")
}
func (UnimplementedSpotifyServer) mustEmbedUnimplementedSpotifyServer() {}
func (UnimplementedSpotifyServer) testEmbeddedByValue()                 {}

// UnsafeSpotifyServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SpotifyServer will
// result in compilation errors.
type UnsafeSpotifyServer interface {
	mustEmbedUnimplementedSpotifyServer()
}

func RegisterSpotifyServer(s grpc.ServiceRegistrar, srv SpotifyServer) {
	// If the following call panics, it indicates UnimplementedSpotifyServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Spotify_ServiceDesc, srv)
}

func _Spotify_GetRecentlyPlayedSong_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRecentlyPlayedSongRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SpotifyServer).GetRecentlyPlayedSong(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Spotify_GetRecentlyPlayedSong_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SpotifyServer).GetRecentlyPlayedSong(ctx, req.(*GetRecentlyPlayedSongRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Spotify_ServiceDesc is the grpc.ServiceDesc for Spotify service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Spotify_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "playground.Spotify",
	HandlerType: (*SpotifyServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetRecentlyPlayedSong",
			Handler:    _Spotify_GetRecentlyPlayedSong_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "playground/spotify.proto",
}
