// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: playground/spotify.proto

package playground

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetRecentlyPlayedSongRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRecentlyPlayedSongRequest) Reset() {
	*x = GetRecentlyPlayedSongRequest{}
	mi := &file_playground_spotify_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRecentlyPlayedSongRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRecentlyPlayedSongRequest) ProtoMessage() {}

func (x *GetRecentlyPlayedSongRequest) ProtoReflect() protoreflect.Message {
	mi := &file_playground_spotify_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRecentlyPlayedSongRequest.ProtoReflect.Descriptor instead.
func (*GetRecentlyPlayedSongRequest) Descriptor() ([]byte, []int) {
	return file_playground_spotify_proto_rawDescGZIP(), []int{0}
}

type GetRecentlyPlayedSongResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Track         string                 `protobuf:"bytes,1,opt,name=track,proto3" json:"track,omitempty"`
	Artist        string                 `protobuf:"bytes,2,opt,name=artist,proto3" json:"artist,omitempty"`
	Playing       bool                   `protobuf:"varint,3,opt,name=playing,proto3" json:"playing,omitempty"`
	AlbumArtUrl   string                 `protobuf:"bytes,4,opt,name=album_art_url,json=albumArtUrl,proto3" json:"album_art_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRecentlyPlayedSongResponse) Reset() {
	*x = GetRecentlyPlayedSongResponse{}
	mi := &file_playground_spotify_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRecentlyPlayedSongResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRecentlyPlayedSongResponse) ProtoMessage() {}

func (x *GetRecentlyPlayedSongResponse) ProtoReflect() protoreflect.Message {
	mi := &file_playground_spotify_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRecentlyPlayedSongResponse.ProtoReflect.Descriptor instead.
func (*GetRecentlyPlayedSongResponse) Descriptor() ([]byte, []int) {
	return file_playground_spotify_proto_rawDescGZIP(), []int{1}
}

func (x *GetRecentlyPlayedSongResponse) GetTrack() string {
	if x != nil {
		return x.Track
	}
	return ""
}

func (x *GetRecentlyPlayedSongResponse) GetArtist() string {
	if x != nil {
		return x.Artist
	}
	return ""
}

func (x *GetRecentlyPlayedSongResponse) GetPlaying() bool {
	if x != nil {
		return x.Playing
	}
	return false
}

func (x *GetRecentlyPlayedSongResponse) GetAlbumArtUrl() string {
	if x != nil {
		return x.AlbumArtUrl
	}
	return ""
}

var File_playground_spotify_proto protoreflect.FileDescriptor

const file_playground_spotify_proto_rawDesc = "" +
	"\n" +
	"\x18playground/spotify.proto\x12\n" +
	"playground\"\x1e\n" +
	"\x1cGetRecentlyPlayedSongRequest\"\x8b\x01\n" +
	"\x1dGetRecentlyPlayedSongResponse\x12\x14\n" +
	"\x05track\x18\x01 \x01(\tR\x05track\x12\x16\n" +
	"\x06artist\x18\x02 \x01(\tR\x06artist\x12\x18\n" +
	"\aplaying\x18\x03 \x01(\bR\aplaying\x12\"\n" +
	"\ralbum_art_url\x18\x04 \x01(\tR\valbumArtUrl2w\n" +
	"\aSpotify\x12l\n" +
	"\x15GetRecentlyPlayedSong\x12(.playground.GetRecentlyPlayedSongRequest\x1a).playground.GetRecentlyPlayedSongResponseB\xb2\x01\n" +
	"\x0ecom.playgroundB\fSpotifyProtoP\x01ZJgithub.com/amirsalarsafaei/amirsalarsafaei.com/autogenerated/go/playground\xa2\x02\x03PXX\xaa\x02\n" +
	"Playground\xca\x02\n" +
	"Playground\xe2\x02\x16Playground\\GPBMetadata\xea\x02\n" +
	"Playgroundb\x06proto3"

var (
	file_playground_spotify_proto_rawDescOnce sync.Once
	file_playground_spotify_proto_rawDescData []byte
)

func file_playground_spotify_proto_rawDescGZIP() []byte {
	file_playground_spotify_proto_rawDescOnce.Do(func() {
		file_playground_spotify_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_playground_spotify_proto_rawDesc), len(file_playground_spotify_proto_rawDesc)))
	})
	return file_playground_spotify_proto_rawDescData
}

var file_playground_spotify_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_playground_spotify_proto_goTypes = []any{
	(*GetRecentlyPlayedSongRequest)(nil),  // 0: playground.GetRecentlyPlayedSongRequest
	(*GetRecentlyPlayedSongResponse)(nil), // 1: playground.GetRecentlyPlayedSongResponse
}
var file_playground_spotify_proto_depIdxs = []int32{
	0, // 0: playground.Spotify.GetRecentlyPlayedSong:input_type -> playground.GetRecentlyPlayedSongRequest
	1, // 1: playground.Spotify.GetRecentlyPlayedSong:output_type -> playground.GetRecentlyPlayedSongResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_playground_spotify_proto_init() }
func file_playground_spotify_proto_init() {
	if File_playground_spotify_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_playground_spotify_proto_rawDesc), len(file_playground_spotify_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_playground_spotify_proto_goTypes,
		DependencyIndexes: file_playground_spotify_proto_depIdxs,
		MessageInfos:      file_playground_spotify_proto_msgTypes,
	}.Build()
	File_playground_spotify_proto = out.File
	file_playground_spotify_proto_goTypes = nil
	file_playground_spotify_proto_depIdxs = nil
}
